import {
  buildHmsStandardDocumentHtml,
  buildHmsTableHtml,
  formatHmsDateTime,
} from '../utils/hms-document-template.util';
import { HmsDocumentHospitalInfo } from '../services/hms-document.types';

export interface DutyRosterDocumentRow {
  staff: string;
  role: string;
  area: string;
  shift: string;
  start: string;
  end: string;
  status: string;
  date?: string;
}

export interface DutyRosterDocumentContext {
  title: string;
  period: string;
  generatedBy?: string;
  hospital?: HmsDocumentHospitalInfo | null;
  filters?: string;
  orientation?: 'portrait' | 'landscape';
  rows: DutyRosterDocumentRow[];
  groups?: Array<{ heading: string; rows: DutyRosterDocumentRow[] }>;
}

function rosterTable(rows: DutyRosterDocumentRow[]): string {
  return buildHmsTableHtml(
    ['Staff', 'Role', 'Ward / Area', 'Shift', 'Start', 'End', 'Status'],
    rows.map((row) => [row.staff, row.role, row.area, row.shift, row.start, row.end, row.status]),
    { emptyMessage: 'No assignments in this period.' }
  );
}

export function buildDutyRosterDocumentHtml(context: DutyRosterDocumentContext): string {
  const grouped = (context.groups || []).filter((group) => group.rows.length);
  const bodyHtml = grouped.length
    ? grouped
        .map(
          (group) => `
      <section class="hms-doc-section">
        <h3>${group.heading}</h3>
        ${rosterTable(group.rows)}
      </section>`
        )
        .join('')
    : `<section class="hms-doc-section"><h3>Assignments</h3>${rosterTable(context.rows)}</section>`;

  return buildHmsStandardDocumentHtml({
    title: context.title,
    hospital: context.hospital,
    dateRangeLabel: 'Period',
    dateRangeValue: context.period,
    orientation: context.orientation || 'portrait',
    metaRows: [
      { label: 'Filters', value: context.filters || 'All areas' },
      { label: 'Generated At', value: formatHmsDateTime(new Date()) },
      { label: 'Generated By', value: context.generatedBy || 'System User' },
    ],
    bodyHtml,
    generatedAt: formatHmsDateTime(new Date()),
    generatedBy: context.generatedBy,
  });
}
