
/* Generated by scripts/run-ward-pure-tests.mjs — safe to delete. */
const state = { passed: 0, failed: 0 };
const suite: string[] = [];

const show = (value: unknown): string => {
  if (typeof value === 'string') return JSON.stringify(value);
  try {
    return JSON.stringify(value);
  } catch {
    return String(value);
  }
};

const fail = (message: string): never => {
  throw new Error(message);
};

const contains = (actual: unknown, expected: unknown): boolean => {
  if (Array.isArray(actual)) return actual.some((item) => show(item) === show(expected));
  return String(actual).includes(String(expected));
};

const build = (actual: unknown, negate: boolean) => {
  const check = (ok: boolean, message: string) => {
    if (negate ? ok : !ok) {
      fail((negate ? 'Expected NOT: ' : 'Expected: ') + message);
    }
  };
  return {
    toBe: (expected: unknown) =>
      check(actual === expected, show(actual) + ' to be ' + show(expected)),
    toEqual: (expected: unknown) =>
      check(show(actual) === show(expected), show(actual) + ' to equal ' + show(expected)),
    toContain: (expected: unknown) =>
      check(contains(actual, expected), show(actual) + ' to contain ' + show(expected)),
    toBeTruthy: () => check(Boolean(actual), show(actual) + ' to be truthy'),
    toBeFalsy: () => check(!actual, show(actual) + ' to be falsy'),
    toBeNull: () => check(actual === null, show(actual) + ' to be null'),
    toBeUndefined: () => check(actual === undefined, show(actual) + ' to be undefined'),
    toBeGreaterThan: (expected: number) =>
      check(Number(actual) > expected, show(actual) + ' to be greater than ' + expected),
    toBeGreaterThanOrEqual: (expected: number) =>
      check(Number(actual) >= expected, show(actual) + ' to be >= ' + expected),
  };
};

const scope = globalThis as Record<string, unknown>;

scope['describe'] = (name: string, fn: () => void) => {
  suite.push(name);
  console.log(name);
  try {
    fn();
  } finally {
    suite.pop();
  }
};

scope['it'] = (name: string, fn: () => void) => {
  try {
    fn();
    state.passed += 1;
    console.log('  ok -', name);
  } catch (error) {
    state.failed += 1;
    console.log('  FAIL -', name, (error as Error)?.message || error);
  }
};

scope['expect'] = (actual: unknown) => ({
  ...build(actual, false),
  not: build(actual, true),
});

scope['beforeEach'] = (fn: () => void) => fn();

scope['__printWardTestSummary'] = () => {
  console.log('\n' + state.passed + ' passed, ' + state.failed + ' failed');
  if (state.failed) process.exit(1);
};
export {};
