
/* Generated by scripts/run-ward-pure-tests.mjs — safe to delete. */
import './_pure-test-globals.tmp';
import './ward-workspace.util.spec';
import './ward-nav.util.spec';
import './ward-home.util.spec';

(globalThis as unknown as { __printWardTestSummary: () => void }).__printWardTestSummary();
