import { WardModulePageConfig } from './ward-module.models';

export const WARD_MODULE_PAGE_CONFIGS: Record<string, WardModulePageConfig> = {
  admissions: {
    key: 'admissions',
    title: 'Admissions',
    subtitle: 'Ward admission requests and active admissions',
    primaryActionLabel: 'New Admission',
    searchPlaceholder: 'Search patient, MRN, bed, doctor...',
    layout: 'table',
    kpis: [
      { label: 'Active Admissions', value: 0, icon: 'fa-bed', tone: 'blue', countTab: 'active' },
      { label: 'Pending Requests', value: 0, icon: 'fa-clock-o', tone: 'orange', countTab: 'pending' },
      { label: 'Discharge Today', value: 0, icon: 'fa-sign-out', tone: 'purple', countTab: 'discharge-today' },
      { label: 'Transfers', value: 0, icon: 'fa-random', tone: 'teal', countTab: 'transfer' },
    ],
    tabs: [
      { key: 'all', label: 'All' },
      { key: 'pending', label: 'Pending Orders' },
      { key: 'active', label: 'Admitted' },
      { key: 'discharge', label: 'Cancelled / Not Admitted' },
    ],
    columns: [
      { key: 'orderNo', label: 'Order No' },
      { key: 'patient', label: 'Patient', type: 'link' },
      { key: 'mrn', label: 'MRN' },
      { key: 'doctor', label: 'Doctor' },
      { key: 'priority', label: 'Priority', type: 'badge' },
      { key: 'reason', label: 'Reason' },
      { key: 'diagnosis', label: 'Diagnosis' },
      { key: 'admittedOn', label: 'Ordered At' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
  },
  'nursing-care': {
    key: 'nursing-care',
    title: 'Nursing Care',
    subtitle: 'Nursing tasks, notes, and care activities for ward patients',
    primaryActionLabel: 'Add Task',
    searchPlaceholder: 'Search patient, task, nurse...',
    layout: 'table',
    kpis: [
      { label: 'Tasks Due', value: 0, icon: 'fa-tasks', tone: 'orange', countTab: 'due' },
      { label: 'Completed', value: 0, icon: 'fa-check', tone: 'green', countTab: 'completed' },
      { label: 'Overdue', value: 0, icon: 'fa-exclamation-triangle', tone: 'red', countTab: 'overdue' },
      { label: 'Notes Today', value: 0, icon: 'fa-sticky-note', tone: 'blue', countTab: 'total' },
    ],
    tabs: [
      { key: 'all', label: 'All Tasks' },
      { key: 'due', label: 'Due' },
      { key: 'completed', label: 'Completed' },
      { key: 'overdue', label: 'Overdue' },
    ],
    columns: [
      { key: 'patient', label: 'Patient', type: 'link' },
      { key: 'task', label: 'Task' },
      { key: 'priority', label: 'Priority', type: 'badge' },
      { key: 'nurse', label: 'Nurse' },
      { key: 'dueAt', label: 'Due At' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
  },
  mar: {
    key: 'mar',
    title: 'MAR / Medications',
    subtitle: 'Medication administration record for ward patients',
    primaryActionLabel: 'Record Dose',
    searchPlaceholder: 'Search patient, medicine, nurse...',
    layout: 'table',
    kpis: [
      { label: 'Due Now', value: 0, icon: 'fa-medkit', tone: 'orange', countTab: 'due' },
      { label: 'Given', value: 0, icon: 'fa-check-circle', tone: 'green', countTab: 'given' },
      { label: 'Missed', value: 0, icon: 'fa-times-circle', tone: 'red', countTab: 'missed' },
      { label: 'PRN Orders', value: 0, icon: 'fa-plus-square', tone: 'purple', countTab: 'total' },
    ],
    tabs: [
      { key: 'all', label: 'All' },
      { key: 'due', label: 'Due' },
      { key: 'given', label: 'Given' },
      { key: 'missed', label: 'Missed' },
    ],
    columns: [
      { key: 'patient', label: 'Patient', type: 'link' },
      { key: 'medicine', label: 'Medicine' },
      { key: 'dose', label: 'Dose' },
      { key: 'route', label: 'Route' },
      { key: 'dueTime', label: 'Due Time' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
  },
  'drips-iv': {
    key: 'drips-iv',
    title: 'Drips / IV Fluids',
    subtitle: 'Running IV fluids and drip management overview',
    primaryActionLabel: 'Start Drip',
    searchPlaceholder: 'Search patient, fluid, bed...',
    layout: 'table',
    kpis: [
      { label: 'Running', value: 0, icon: 'fa-tint', tone: 'blue', countTab: 'running' },
      { label: 'Planned', value: 0, icon: 'fa-clock-o', tone: 'orange', countTab: 'planned' },
      { label: 'Completed', value: 0, icon: 'fa-check', tone: 'green', countTab: 'completed' },
      { label: 'Total', value: 0, icon: 'fa-list', tone: 'teal', countTab: 'total' },
    ],
    tabs: [
      { key: 'all', label: 'All' },
      { key: 'planned', label: 'Planned' },
      { key: 'running', label: 'Running' },
      { key: 'completed', label: 'Completed' },
      { key: 'alerts', label: 'Alerts' },
    ],
    columns: [
      { key: 'patient', label: 'Patient', type: 'link' },
      { key: 'fluid', label: 'Fluid' },
      { key: 'rate', label: 'Rate' },
      { key: 'startedAt', label: 'Started' },
      { key: 'nurse', label: 'Nurse' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
  },
  vitals: {
    key: 'vitals',
    title: 'Vitals & Observations',
    subtitle: 'Patient vitals schedule, recordings, and due observations',
    primaryActionLabel: 'Record Vitals',
    searchPlaceholder: 'Search patient, bed, nurse...',
    layout: 'table',
    kpis: [
      { label: 'Recorded', value: 0, icon: 'fa-check', tone: 'green', countTab: 'recorded' },
      { label: 'Due', value: 0, icon: 'fa-heartbeat', tone: 'orange', countTab: 'due' },
      { label: 'Patients', value: 0, icon: 'fa-users', tone: 'blue', countTab: 'unique-patient' },
      { label: 'Total Entries', value: 0, icon: 'fa-list', tone: 'teal', countTab: 'total' },
    ],
    tabs: [
      { key: 'all', label: 'All' },
      { key: 'due', label: 'Due' },
      { key: 'recorded', label: 'Recorded' },
      { key: 'critical', label: 'Critical' },
    ],
    columns: [
      { key: 'patient', label: 'Patient', type: 'link' },
      { key: 'bed', label: 'Bed' },
      { key: 'recordedAt', label: 'Recorded' },
      { key: 'bp', label: 'BP' },
      { key: 'temp', label: 'Temp' },
      { key: 'pulse', label: 'Pulse' },
      { key: 'spo2', label: 'SpO2' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
  },
  'io-chart': {
    key: 'io-chart',
    title: 'I/O Chart',
    subtitle: 'Intake and output monitoring for admitted patients',
    primaryActionLabel: 'Add Entry',
    searchPlaceholder: 'Search patient, bed...',
    layout: 'table',
    kpis: [
      { label: 'Patients Tracked', value: 0, icon: 'fa-users', tone: 'blue', countTab: 'unique-patient' },
      { label: 'Positive Balance', value: 0, icon: 'fa-arrow-up', tone: 'green', countTab: 'positive' },
      { label: 'Negative Balance', value: 0, icon: 'fa-arrow-down', tone: 'orange', countTab: 'negative' },
      { label: 'Alerts', value: 0, icon: 'fa-bell', tone: 'red', countTab: 'alerts' },
    ],
    tabs: [
      { key: 'all', label: 'All' },
      { key: 'shift', label: 'This Shift' },
      { key: 'alerts', label: 'Alerts' },
    ],
    columns: [
      { key: 'patient', label: 'Patient', type: 'link' },
      { key: 'intake', label: 'Intake (ml)' },
      { key: 'output', label: 'Output (ml)' },
      { key: 'balance', label: 'Balance' },
      { key: 'shift', label: 'Shift' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
  },
  'orders-services': {
    key: 'orders-services',
    title: 'Orders & Services',
    subtitle: 'Doctor orders, investigations, and ward services',
    primaryActionLabel: 'New Order',
    searchPlaceholder: 'Search patient, order, doctor...',
    layout: 'table',
    kpis: [
      { label: 'Pending', value: 0, icon: 'fa-file-text-o', tone: 'orange', countTab: 'pending' },
      { label: 'In Progress', value: 0, icon: 'fa-spinner', tone: 'blue', countTab: 'progress' },
      { label: 'Completed', value: 0, icon: 'fa-check', tone: 'green', countTab: 'completed' },
      { label: 'Urgent', value: 0, icon: 'fa-bolt', tone: 'red', countTab: 'urgent' },
    ],
    tabs: [
      { key: 'all', label: 'All' },
      { key: 'pending', label: 'Pending' },
      { key: 'progress', label: 'In Progress' },
      { key: 'completed', label: 'Completed' },
    ],
    columns: [
      { key: 'patient', label: 'Patient', type: 'link' },
      { key: 'order', label: 'Order' },
      { key: 'type', label: 'Type' },
      { key: 'doctor', label: 'Doctor' },
      { key: 'time', label: 'Time' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
  },
  'shift-handover': {
    key: 'shift-handover',
    title: 'Shift Handover',
    subtitle: 'Nursing shift handover notes and pending handoffs',
    primaryActionLabel: 'Create Handover',
    searchPlaceholder: 'Search nurse, shift, patient...',
    layout: 'table',
    kpis: [
      { label: 'Handovers Today', value: 0, icon: 'fa-exchange', tone: 'blue', countTab: 'total' },
      { label: 'Pending Items', value: 0, icon: 'fa-list', tone: 'orange', countTab: 'pending' },
      { label: 'Critical Notes', value: 0, icon: 'fa-exclamation-triangle', tone: 'red', countTab: 'critical' },
      { label: 'Completed', value: 0, icon: 'fa-check', tone: 'green', countTab: 'completed' },
    ],
    tabs: [
      { key: 'all', label: 'All' },
      { key: 'day', label: 'Day Shift' },
      { key: 'evening', label: 'Evening' },
      { key: 'night', label: 'Night' },
    ],
    columns: [
      { key: 'shift', label: 'Shift' },
      { key: 'nurse', label: 'Nurse' },
      { key: 'patient', label: 'Patient', type: 'link' },
      { key: 'condition', label: 'Condition' },
      { key: 'pending', label: 'Pending Items' },
      { key: 'risk', label: 'Risk Alerts' },
      { key: 'updatedAt', label: 'Updated' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
  },
  inventory: {
    key: 'inventory',
    title: 'Ward Inventory',
    subtitle: 'Ward supplies, consumables, and stock levels',
    primaryActionLabel: 'Add Item',
    searchPlaceholder: 'Search item, category...',
    layout: 'table',
    kpis: [
      { label: 'Total Items', value: 0, icon: 'fa-cubes', tone: 'blue', countTab: 'total' },
      { label: 'Low Stock', value: 0, icon: 'fa-arrow-down', tone: 'orange', countTab: 'low' },
      { label: 'Out of Stock', value: 0, icon: 'fa-times', tone: 'red', countTab: 'out' },
      { label: 'Requested', value: 0, icon: 'fa-shopping-cart', tone: 'purple', countTab: 'requested' },
    ],
    tabs: [
      { key: 'all', label: 'All' },
      { key: 'low', label: 'Low Stock' },
      { key: 'out', label: 'Out of Stock' },
      { key: 'requested', label: 'Requested' },
    ],
    columns: [
      { key: 'item', label: 'Item' },
      { key: 'category', label: 'Category' },
      { key: 'stock', label: 'Stock' },
      { key: 'reorder', label: 'Reorder Level' },
      { key: 'location', label: 'Location' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
  },
  reports: {
    key: 'reports',
    title: 'Ward Reports',
    subtitle: 'Occupancy, nursing, medication, and ward performance reports',
    searchPlaceholder: 'Search report...',
    layout: 'reports',
    kpis: [
      { label: 'Saved Reports', value: 0, icon: 'fa-file-text', tone: 'blue', countTab: 'total' },
      { label: 'Scheduled', value: 0, icon: 'fa-calendar', tone: 'purple', countTab: 'scheduled' },
      { label: 'Generated Today', value: 0, icon: 'fa-line-chart', tone: 'green', countTab: 'today' },
      { label: 'Alerts', value: 0, icon: 'fa-bell', tone: 'red', countTab: 'alerts' },
    ],
    tabs: [
      { key: 'all', label: 'All Reports' },
      { key: 'occupancy', label: 'Occupancy' },
      { key: 'nursing', label: 'Nursing' },
      { key: 'medication', label: 'Medication' },
    ],
    columns: [],
  },
};

export const WARD_HIERARCHY_NODES = [
  { id: 'b1', label: 'Main Hospital Building', level: 1, icon: 'fa-hospital-o' },
  { id: 'f2', label: 'Floor 2 — Paediatrics', level: 2, icon: 'fa-building' },
  { id: 'w1', label: 'Peads Ward', level: 3, icon: 'fa-heartbeat' },
  { id: 'g1', label: 'Gallery A — Male', level: 4, icon: 'fa-th-large' },
  { id: 'r101', label: 'Room 101 (6 beds)', level: 5, icon: 'fa-bed' },
  { id: 'g2', label: 'Gallery B — Female', level: 4, icon: 'fa-th-large' },
  { id: 'r103', label: 'Room 103 (4 beds)', level: 5, icon: 'fa-bed' },
  { id: 'pw', label: 'Private Wing', level: 3, icon: 'fa-star' },
  { id: 'icu', label: 'ICU Wing', level: 3, icon: 'fa-plus-square' },
];
