export interface HelpArticle {
  id: string;
  slug: string;
  title: string;
  category: string;
  keywords: string[];
  /** Extra search phrases (Urdu/Roman, common typos) */
  searchAliases?: string[];
  /** One-line summary for search results */
  shortDescription?: string;
  /** When do I use this? */
  whenToUse?: string;
  /** Optional staff tip box on guide detail */
  tip?: string;
  /** User-facing menu path for Where to go */
  navigationPath?: string[];
  whoCan: string;
  permissions: string;
  /** Role filter keys: owner, doctor, nurse, receptionist, laboratory, pharmacy, accountant, ward */
  roles?: string[];
  /** Module gating for module guides */
  module?: 'clinical' | 'pharmacy' | 'laboratory' | 'ward' | 'accounts' | 'setup' | 'nursery';
  beforeStart: string[];
  steps: string[];
  after: string[];
  financial?: string[];
  errors?: string[];
  related: string[];
  route?: string;
}

export interface HelpQuickTask {
  label: string;
  slug: string;
  icon: string;
}

export interface HelpModuleGuide {
  key: string;
  title: string;
  description: string;
  icon: string;
  module: HelpArticle['module'];
  category: string;
  slug?: string;
}

export const HELP_CATEGORIES = [
  'Getting Started',
  'Patients',
  'Appointments / OPD',
  'Doctors / Prescriptions',
  'Admissions / IPD',
  'Ward / Room / Bed',
  'Nursing',
  'Pharmacy',
  'Laboratory',
  'Imaging / X-Ray',
  'Procedures / Operations',
  'Billing / Accounts',
  'Reports',
  'Nursery / Newborn',
  'Birth Records / Certificates',
  'Roles & Permissions',
  'Troubleshooting',
] as const;

/** Common search aliases → article slugs */
export const HELP_SEARCH_ALIASES: Record<string, string[]> = {
  'admit patient': ['how-to-admit-patient', 'doctor-recommend-admission'],
  admit: ['how-to-admit-patient', 'doctor-recommend-admission'],
  admission: ['how-to-admit-patient', 'doctor-recommend-admission', 'room-bed-hierarchy'],
  'ward admission': ['how-to-admit-patient', 'doctor-recommend-admission'],
  'patient admit kaise karein': ['how-to-admit-patient', 'doctor-recommend-admission'],
  'doctor ne admit forward kiya': ['how-to-admit-patient', 'doctor-recommend-admission'],
  'ward me patient admit karna': ['how-to-admit-patient'],
  'room allotment': ['how-to-admit-patient', 'room-bed-hierarchy', 'create-rooms-beds'],
  'bed assign': ['how-to-admit-patient', 'room-bed-hierarchy', 'create-rooms-beds'],
  ward: ['how-to-admit-patient', 'ward-nursing-care', 'room-bed-hierarchy', 'ward-control-panel'],
  room: ['room-bed-hierarchy', 'create-rooms-beds', 'how-to-admit-patient'],
  bed: ['room-bed-hierarchy', 'create-rooms-beds', 'how-to-admit-patient'],
  'appointment create': ['how-to-create-appointment'],
  appointment: ['how-to-create-appointment', 'doctor-consultation-flow'],
  'doctor add': ['add-doctor-guide'],
  doctor: ['doctor-consultation-flow', 'add-doctor-guide'],
  medicine: ['pharmacy-ward-medicine', 'mar-medicine-guide'],
  'medicine dose': ['mar-medicine-guide', 'pharmacy-ward-medicine'],
  'medicine kab deni hai': ['mar-medicine-guide'],
  mar: ['mar-medicine-guide', 'ward-nursing-care'],
  'lab test': ['lab-order-from-ward', 'laboratory-orders'],
  lab: ['laboratory-orders', 'lab-order-from-ward'],
  cbc: ['lab-order-from-ward', 'laboratory-orders'],
  'blood test': ['laboratory-orders', 'lab-order-from-ward'],
  xray: ['radiology-imaging-guide'],
  'x-ray': ['radiology-imaging-guide'],
  radiology: ['radiology-imaging-guide'],
  scan: ['radiology-imaging-guide'],
  'pharmacy sale': ['pharmacy-ward-medicine'],
  pos: ['pharmacy-ward-medicine'],
  'medicine issue': ['pharmacy-ward-medicine'],
  payment: ['receive-patient-payment', 'patient-ledger-payments'],
  cash: ['patient-ledger-payments', 'receive-patient-payment'],
  invoice: ['how-to-discharge-patient', 'patient-ledger-payments'],
  bill: ['how-to-discharge-patient', 'patient-ledger-payments'],
  ledger: ['patient-ledger-payments', 'accounts-overview'],
  discharge: ['how-to-discharge-patient'],
  'previous admission': ['admission-history-guide'],
  baby: ['maternity-newborn-flow', 'birth-certificate-issue', 'register-newborn'],
  newborn: ['maternity-newborn-flow', 'register-newborn'],
  'birth certificate': ['birth-certificate-issue'],
  'baby certificate': ['birth-certificate-issue'],
  'qr verify': ['birth-certificate-issue'],
  'medicine kaise issue karein': ['pharmacy-ward-medicine'],
};

export const HELP_QUICK_TASKS: HelpQuickTask[] = [
  { label: 'Register Patient', slug: 'how-to-register-patient', icon: 'fa-user-plus' },
  { label: 'Create Appointment', slug: 'how-to-create-appointment', icon: 'fa-calendar' },
  { label: 'Add Doctor', slug: 'add-doctor-guide', icon: 'fa-user-md' },
  { label: 'Recommend Admission', slug: 'doctor-recommend-admission', icon: 'fa-hospital-o' },
  { label: 'Admit Patient', slug: 'how-to-admit-patient', icon: 'fa-bed' },
  { label: 'Allocate Room / Bed', slug: 'room-bed-hierarchy', icon: 'fa-building' },
  { label: 'Record Vitals', slug: 'ward-nursing-care', icon: 'fa-heartbeat' },
  { label: 'Give Medicine / MAR', slug: 'mar-medicine-guide', icon: 'fa-medkit' },
  { label: 'Order Lab Test', slug: 'lab-order-from-ward', icon: 'fa-flask' },
  { label: 'Order X-Ray / Imaging', slug: 'radiology-imaging-guide', icon: 'fa-picture-o' },
  { label: 'Pharmacy Issue', slug: 'pharmacy-ward-medicine', icon: 'fa-shopping-cart' },
  { label: 'Receive Payment', slug: 'receive-patient-payment', icon: 'fa-money' },
  { label: 'Discharge Patient', slug: 'how-to-discharge-patient', icon: 'fa-sign-out' },
  { label: 'Register Newborn', slug: 'register-newborn', icon: 'fa-child' },
  { label: 'Issue Birth Certificate', slug: 'birth-certificate-issue', icon: 'fa-certificate' },
];

export const HELP_MODULE_GUIDES: HelpModuleGuide[] = [
  { key: 'clinical', title: 'Clinical & OPD', description: 'Patients, appointments, doctors, prescriptions', icon: 'fa-stethoscope', module: 'clinical', category: 'Appointments / OPD', slug: 'how-to-create-appointment' },
  { key: 'ward', title: 'Ward & Nursing', description: 'Admissions, beds, vitals, MAR, discharge', icon: 'fa-heartbeat', module: 'ward', category: 'Admissions / IPD', slug: 'how-to-admit-patient' },
  { key: 'laboratory', title: 'Laboratory', description: 'Lab orders, samples, results, reports', icon: 'fa-flask', module: 'laboratory', category: 'Laboratory', slug: 'laboratory-orders' },
  { key: 'pharmacy', title: 'Pharmacy', description: 'POS, ward requests, stock, issue medicine', icon: 'fa-medkit', module: 'pharmacy', category: 'Pharmacy', slug: 'pharmacy-ward-medicine' },
  { key: 'accounts', title: 'Accounts & Billing', description: 'Ledger, payments, GL, reports', icon: 'fa-book', module: 'accounts', category: 'Billing / Accounts', slug: 'accounts-overview' },
  { key: 'nursery', title: 'Nursery / Newborn', description: 'Birth records, newborn care, certificates', icon: 'fa-child', module: 'nursery', category: 'Nursery / Newborn', slug: 'maternity-newborn-flow' },
  { key: 'setup', title: 'Hospital Setup', description: 'Departments, wards, rooms, users', icon: 'fa-hospital-o', module: 'setup', category: 'Getting Started', slug: 'hospital-setup-guide' },
  { key: 'roles', title: 'Roles & Permissions', description: 'Users, roles, and hospital access', icon: 'fa-shield', module: 'setup', category: 'Roles & Permissions', slug: 'roles-permissions' },
];

export const HELP_POPULAR_SEARCHES = [
  'admit patient',
  'medicine dose',
  'lab test',
  'x-ray',
  'payment',
  'birth certificate',
] as const;

export const HELP_ROLE_FILTERS = [
  { key: '', label: 'All Roles' },
  { key: 'owner', label: 'Owner / Admin' },
  { key: 'receptionist', label: 'Receptionist' },
  { key: 'doctor', label: 'Doctor' },
  { key: 'ward', label: 'Ward Receptionist / Nurse' },
  { key: 'laboratory', label: 'Laboratory' },
  { key: 'pharmacy', label: 'Pharmacy' },
  { key: 'accountant', label: 'Accountant' },
] as const;

export const HELP_ARTICLES: HelpArticle[] = [
  {
    id: 'getting-started-overview',
    slug: 'getting-started-overview',
    title: 'Hisaar360 HMS Overview',
    category: 'Getting Started',
    keywords: ['start', 'overview', 'hms', 'dashboard', 'workflow'],
    whoCan: 'All logged-in users',
    permissions: 'Depends on role',
    beforeStart: ['You must be logged in with an active hospital context.'],
    steps: [
      'Open Dashboard from the left menu.',
      'Use the sidebar to reach Patients, Appointments, Ward, Pharmacy, Laboratory, Accounts, and Reports.',
      'Your visible menu items depend on your role permissions.',
    ],
    after: ['You can navigate to module-specific guides from Help Center search.'],
    related: ['how-to-register-patient', 'how-to-create-appointment', 'room-bed-hierarchy'],
  },
  {
    id: 'how-to-register-patient',
    slug: 'how-to-register-patient',
    title: 'How to Register a Patient',
    category: 'Patients',
    keywords: ['patient', 'register', 'mr', 'create patient'],
    whoCan: 'Appointment Receptionist, Ward Receptionist, Company Owner',
    permissions: 'patients.create',
    route: '/add-patient',
    beforeStart: ['Confirm CNIC/phone if your hospital requires them.'],
    steps: [
      'Go to Patients → Add Patient (`/add-patient`).',
      'Enter name, gender, date of birth, phone, and address.',
      'Save — the system assigns MR No (patientNo) automatically.',
    ],
    after: ['Patient appears in All Patients and can be used for appointments and admissions.'],
    related: ['how-to-create-appointment', 'how-to-admit-patient'],
  },
  {
    id: 'how-to-create-appointment',
    slug: 'how-to-create-appointment',
    title: 'How to Create an Appointment',
    category: 'Appointments / OPD',
    keywords: ['appointment', 'opd', 'schedule', 'consultation', 'appointment create'],
    searchAliases: ['appointment create', 'book appointment', 'opd appointment'],
    whoCan: 'Appointment Receptionist',
    permissions: 'appointments.create',
    route: '/appointments',
    beforeStart: ['Patient must exist. Doctor and Department must be active.'],
    steps: [
      'Open Appointments (`/appointments`).',
      'Create appointment: select patient, doctor, department, date/time.',
      'Set consultation fee if applicable and save.',
      'Collect OPD payment through supported payment workflow when required.',
    ],
    after: ['Appointment appears in doctor schedule and OPD queue. Consultation fee posts to encounter ledger when consultation is completed.'],
    financial: ['Consultation fee creates one ledger charge and one GL revenue event when finalized — not at booking alone unless configured.'],
    related: ['doctor-consultation-flow', 'how-to-admit-patient'],
  },
  {
    id: 'doctor-consultation-flow',
    slug: 'doctor-consultation-flow',
    title: 'Doctor Consultation & Prescription',
    category: 'Doctors / Prescriptions',
    keywords: ['doctor', 'consultation', 'prescription', 'diagnosis', 'admission order'],
    shortDescription: 'Complete OPD consultation, write prescription, and recommend admission when needed.',
    whenToUse: 'When a patient arrives for a scheduled appointment or walk-in consultation.',
    whoCan: 'Doctor',
    permissions: 'prescriptions.create',
    roles: ['doctor'],
    module: 'clinical',
    route: '/prescriptions',
    beforeStart: ['Patient must have an active appointment or encounter.'],
    steps: [
      'Open Prescriptions → New Prescription (`/prescriptions`).',
      'Select patient/appointment and enter clinical notes, diagnosis, medicines, lab orders.',
      'Use Admission Orders drawer to Recommend Admission when IPD is needed.',
      'Save prescription — admission recommendation does NOT allocate room/bed.',
    ],
    after: ['Prescription saved. Admission recommendation appears in Ward → Admissions → Pending.'],
    financial: ['Admission recommendation alone creates no room charge, no admission encounter, and no revenue.'],
    errors: ['If Recommend Admission is missing, check doctor permissions and prescription module access.'],
    related: ['doctor-recommend-admission', 'how-to-admit-patient', 'room-bed-hierarchy'],
  },
  {
    id: 'doctor-recommend-admission',
    slug: 'doctor-recommend-admission',
    title: 'Doctor: Recommend a Patient for Admission',
    category: 'Admissions / IPD',
    keywords: ['recommend admission', 'admission order', 'pending', 'ipd', 'doctor'],
    searchAliases: ['admission recommend', 'admit order', 'patient admit kaise karein doctor'],
    shortDescription: 'Doctor sends patient to Ward Reception — patient is NOT admitted yet.',
    whenToUse: 'After consultation when inpatient care is required.',
    whoCan: 'Doctor',
    permissions: 'prescriptions.create',
    roles: ['doctor'],
    module: 'clinical',
    route: '/prescriptions',
    navigationPath: ['Prescriptions', 'Admission Orders', 'Recommend Admission'],
    tip: 'Success message shows Order No — patient is recommended, not admitted yet.',
    beforeStart: ['Patient consultation or prescription in progress.'],
    steps: [
      'Open Appointment → start Consultation → Prescription → Admission Orders → Recommend Admission.',
      'Select recommended ward, priority, clinical reason, and supporting notes.',
      'Click Recommend Admission — success shows Order No and “WHAT HAPPENS NEXT”.',
      'RESULT: Admission Recommendation only (status pending). NO RoomAllotment. NO admission Encounter.',
      'Ward Reception receives a notification and completes Review & Admit separately.',
    ],
    after: ['Pending admission appears in Ward → Admissions → Pending Admissions tab.'],
    financial: ['No revenue, no admission encounter, no bed charge at recommendation stage.'],
    errors: ['Do not tell patient they are admitted — only recommended.'],
    related: ['how-to-admit-patient', 'doctor-consultation-flow'],
  },
  {
    id: 'how-to-admit-patient',
    slug: 'how-to-admit-patient',
    title: 'Ward Reception: Complete Patient Admission',
    category: 'Admissions / IPD',
    keywords: ['admit', 'admission', 'ward reception', 'ipd', 'pending'],
    searchAliases: ['patient admit kaise karein', 'admit patient', 'ward admit', 'doctor ne admit forward kiya', 'ward me patient admit karna'],
    shortDescription: 'Ward Reception performs actual admission with ward, room, and bed.',
    whenToUse: 'After a Doctor recommends admission.',
    whoCan: 'Ward Receptionist',
    permissions: 'room_allotments.create',
    roles: ['ward', 'owner'],
    module: 'ward',
    route: '/ward/admissions',
    navigationPath: ['Ward & Nursing', 'Admissions', 'Pending Admissions'],
    tip: 'Doctor recommendation alone does not admit the patient — Ward Reception completes Review & Admit.',
    beforeStart: ['Doctor Admission Recommendation must exist in Ward → Admissions → Pending.'],
    steps: [
      'Open Ward & Nursing → Admissions → Pending Admissions.',
      'Open the doctor recommendation (or notification) → Review & Admit.',
      'Select Ward → Room → Bed, consultant, optional nurse, advance/security if needed.',
      'Confirm Admit Patient.',
      'RESULT: one RoomAllotment + one admission Encounter + bed becomes occupied.',
      'Success screen shows Admission No and Open Patient Control Panel.',
    ],
    after: ['Patient appears in Ward patient list. Room/bed becomes occupied.'],
    financial: ['Advance/security may be collected as ledger payment — not revenue. Bed charges accrue per billing rules.'],
    errors: ['Occupied beds cannot be double-assigned. Inactive wards/rooms are not offered.'],
    related: ['doctor-recommend-admission', 'room-bed-hierarchy', 'how-to-discharge-patient'],
  },
  {
    id: 'add-doctor-guide',
    slug: 'add-doctor-guide',
    title: 'How to Add a Doctor',
    category: 'Doctors / Prescriptions',
    keywords: ['add doctor', 'create doctor', 'doctor kaise banaye', 'schedule', 'doctor add'],
    searchAliases: ['doctor add', 'new doctor', 'create doctor profile'],
    shortDescription: 'Register a new doctor with department and schedule.',
    whoCan: 'Hospital Admin, Owner',
    permissions: 'doctors.create',
    roles: ['owner'],
    module: 'clinical',
    route: '/add-doctors',
    beforeStart: ['Department must exist in Hospital Setup.'],
    steps: [
      'Open Doctors → Add Doctors (`/add-doctors`).',
      'Enter doctor name, specialty, department, contact, and fee if applicable.',
      'Save and optionally set Doctors Schedule (`/doctors-schedule`).',
    ],
    after: ['Doctor appears in appointment booking and prescription flows.'],
    related: ['how-to-create-appointment', 'doctor-consultation-flow'],
  },
  {
    id: 'hospital-setup-guide',
    slug: 'hospital-setup-guide',
    title: 'Initial Hospital Setup',
    category: 'Getting Started',
    keywords: ['setup', 'departments', 'wards', 'users', 'hospital admin'],
    shortDescription: 'Configure departments, wards, rooms, and users for go-live.',
    whoCan: 'Owner / Hospital Admin',
    permissions: 'hospitals.update',
    roles: ['owner'],
    module: 'setup',
    route: '/hospital-setup',
    beforeStart: ['Owner or hospital setup permission required.'],
    steps: [
      'Open Hospital Setup (`/hospital-setup`).',
      'Create Departments (clinical specialties).',
      'Create Wards linked to departments where applicable.',
      'Add Rooms & Beds under each ward (see Create Rooms & Beds guide).',
      'Create Users & assign Roles with correct permissions.',
    ],
    after: ['Clinical, ward, and billing workflows can use configured master data.'],
    related: ['create-rooms-beds', 'roles-permissions'],
  },
  {
    id: 'create-rooms-beds',
    slug: 'create-rooms-beds',
    title: 'How to Create Rooms & Beds',
    category: 'Ward / Room / Bed',
    keywords: ['create room', 'create bed', 'room kaise banaye', 'bed management'],
    shortDescription: 'Set up physical rooms and beds under wards.',
    whenToUse: 'During initial setup or when expanding ward capacity.',
    whoCan: 'Owner / Hospital Admin / Ward Admin',
    permissions: 'rooms.create',
    roles: ['owner', 'ward'],
    module: 'ward',
    route: '/hospital-setup',
    beforeStart: ['Ward must exist in Hospital Setup.'],
    steps: [
      'Open Hospital Setup → Rooms / Beds (`/hospital-setup`, Rooms tab).',
      'Select ward (and floor if used).',
      'Add Room with room type and rate.',
      'Add beds/cots under the room with bed labels.',
      'Use Ward → Bed Management to verify Available / Occupied status.',
    ],
    after: ['Beds appear for admission and nursery cot allocation.'],
    related: ['room-bed-hierarchy', 'how-to-admit-patient'],
  },
  {
    id: 'ward-control-panel',
    slug: 'ward-control-panel',
    title: 'Ward Patient Control Panel',
    category: 'Nursing',
    keywords: ['control panel', 'patient detail', 'ward patient', 'overview'],
    shortDescription: 'Central screen for one admitted patient — vitals, MAR, orders, billing.',
    whenToUse: 'After admission when managing inpatient care.',
    whoCan: 'Nurse, Ward Doctor, Ward Receptionist',
    permissions: 'ward.read',
    roles: ['ward', 'doctor'],
    module: 'ward',
    route: '/ward/patient-detail',
    beforeStart: ['Patient must be admitted with active encounter.'],
    steps: [
      'From Ward Patient List or Admissions, open patient detail.',
      'Review header: MR, admission no, ward/room/bed, consultant, diagnosis.',
      'Use action bar: Vitals, Medicine/MAR, Lab, Orders, Payment, Discharge.',
      'Use tabs for Overview, Medicines, Lab, Billing, Discharge, etc.',
    ],
    after: ['All ward activities link to the same admission encounter.'],
    related: ['ward-nursing-care', 'mar-medicine-guide', 'how-to-discharge-patient'],
  },
  {
    id: 'mar-medicine-guide',
    slug: 'mar-medicine-guide',
    title: 'Give Medicine / MAR',
    category: 'Nursing',
    keywords: ['mar', 'medicine', 'dose', 'medicine dose', 'administer', 'schedule'],
    searchAliases: ['medicine dose', 'give medicine', 'last given', 'next due', 'medicine kab deni hai', 'administer medicine'],
    shortDescription: 'Track ordered medicine, pharmacy issue, and each administered dose.',
    whenToUse: 'When inpatient medicines are ordered and need scheduled administration.',
    whoCan: 'Nurse',
    permissions: 'ward.nursing.read',
    roles: ['ward', 'doctor'],
    module: 'ward',
    route: '/ward/mar',
    beforeStart: ['Medicine ordered and pharmacy issue completed where applicable.'],
    steps: [
      'Doctor Order → medicine added (ORDERED / Recommended By doctor preserved).',
      'Nurse sends Medicine Request to Pharmacy (REQUESTED / Entered By nurse).',
      'Pharmacy issues stock (ISSUED / Issued By pharmacy user).',
      'Open Ward Patient Control Panel → Medicines / MAR or Ward → MAR.',
      'Review Last Given, Next Due, and Dose Timeline (Due, Late, Given, Held, Refused).',
      'Click a due dose → Record Administration with scheduled time, actual dose, and status.',
      'RESULT: GIVEN dose recorded with administeredBy and administeredAt — prior doses are never overwritten.',
    ],
    after: ['ORDERED ≠ REQUESTED ≠ ISSUED ≠ GIVEN — each step has a different actor and status.'],
    related: ['pharmacy-ward-medicine', 'ward-control-panel'],
  },
  {
    id: 'lab-order-from-ward',
    slug: 'lab-order-from-ward',
    title: 'Order Lab Test for Admitted Patient',
    category: 'Laboratory',
    keywords: ['lab test', 'cbc', 'blood test', 'lab order', 'lab kaise karein'],
    searchAliases: ['lab test', 'order lab', 'cbc test'],
    shortDescription: 'Order laboratory tests for an admitted patient.',
    whenToUse: 'When doctor or nurse needs new lab work during admission.',
    whoCan: 'Doctor, Nurse (on behalf of doctor)',
    permissions: 'lab_orders.create',
    roles: ['doctor', 'ward'],
    module: 'laboratory',
    route: '/ward/orders-services',
    beforeStart: ['Patient admitted with active encounter.'],
    steps: [
      'Doctor or Nurse (on behalf) opens Ward Patient Control Panel → Doctor Order → Lab.',
      'Laboratory receives order in Lab Dashboard.',
      'Lab: Collect Sample → Enter Result → Verify.',
      'Ward/Doctor receives Lab Result Ready notification.',
      'Open result from Control Panel → Laboratory tab (read-only verified result).',
    ],
    after: ['Verified result visible on ward/doctor view; charge posts to encounter ledger.'],
    related: ['laboratory-orders', 'ward-control-panel'],
  },
  {
    id: 'radiology-imaging-guide',
    slug: 'radiology-imaging-guide',
    title: 'X-Ray / Imaging Order',
    category: 'Imaging / X-Ray',
    keywords: ['xray', 'x-ray', 'radiology', 'imaging', 'scan', 'chest x-ray'],
    searchAliases: ['xray kaise karein', 'x ray order', 'xray', 'x-ray', 'scan order'],
    shortDescription: 'Imaging via Ward Doctor Orders — no dedicated Radiology module yet.',
    whenToUse: 'When imaging (e.g. Chest X-Ray) is needed during inpatient care.',
    whoCan: 'Doctor, Nurse (on behalf of doctor)',
    permissions: 'ward.read',
    roles: ['doctor', 'ward'],
    module: 'ward',
    route: '/ward/orders-services',
    beforeStart: ['Patient admitted; imaging service configured if billable.'],
    steps: [
      'Open Ward Patient Control Panel → Doctor Order → Imaging.',
      'Imaging orders such as X-Ray, Ultrasound, CT and MRI are currently recorded through Ward Doctor Orders.',
      'Select modality (e.g. X-Ray), study name, priority, and clinical indication.',
      'If nurse enters on behalf, set Recommended By doctor.',
      'Order appears in Control Panel → Imaging tab and ward notifications where configured.',
      'There is no separate Radiology module in the current release.',
    ],
    after: ['Order tracked on patient record; report available for clinical review.'],
    related: ['ward-control-panel', 'operations-procedures'],
  },
  {
    id: 'receive-patient-payment',
    slug: 'receive-patient-payment',
    title: 'How to Receive Patient Payment',
    category: 'Billing / Accounts',
    keywords: ['payment', 'receive payment', 'cash', 'payment kaise receive karein'],
    searchAliases: ['payment kaise karein', 'collect payment'],
    shortDescription: 'Collect cash/card payment against patient encounter balance.',
    whoCan: 'Cashier, Ward Receptionist, Accountant',
    permissions: 'ledger_payments.create',
    roles: ['accountant', 'ward', 'owner'],
    module: 'accounts',
    route: '/payments/addpayment',
    beforeStart: ['Patient encounter with outstanding or advance collection needed.'],
    steps: [
      'Open Payments → Add Payment (`/payments/addpayment`) or ward payment action.',
      'Select patient and encounter; enter amount and payment method.',
      'Save — receipt number generated in ledger_payments.',
    ],
    after: ['Balance updated; appears in Daily Collections and GL.'],
    financial: ['Payment is ledger_payment — not counted as duplicate revenue.'],
    related: ['patient-ledger-payments', 'how-to-discharge-patient'],
  },
  {
    id: 'register-newborn',
    slug: 'register-newborn',
    title: 'Register Newborn & Link to Mother',
    category: 'Nursery / Newborn',
    keywords: ['register newborn', 'baby', 'link mother', 'nursery'],
    shortDescription: 'Create baby patient record and nursery placement after delivery.',
    whoCan: 'Nursery / Ward staff',
    permissions: 'nursery.read',
    roles: ['ward', 'doctor'],
    module: 'nursery',
    route: '/ward/nursery/birth-records',
    beforeStart: ['Mother admitted; birth event documented.'],
    steps: [
      'Open Birth Records (`/ward/nursery/birth-records`) → Record Birth.',
      'Search mother by name/MR; enter delivery details.',
      'System creates newborn Patient with own MR and links to mother.',
      'Assign nursery cot in Nursery dashboard if applicable.',
    ],
    after: ['Baby has separate encounter for treatments and billing.'],
    related: ['maternity-newborn-flow', 'birth-certificate-issue'],
  },
  {
    id: 'room-bed-hierarchy',
    slug: 'room-bed-hierarchy',
    title: 'Department vs Ward vs Room vs Bed',
    category: 'Ward / Room / Bed',
    keywords: ['room', 'bed', 'ward', 'floor', 'transfer', 'cot', 'department', 'room allotment', 'bed assign'],
    searchAliases: ['room allotment', 'bed assign', 'allocate room', 'allocate bed'],
    whoCan: 'All clinical and ward staff',
    permissions: 'ward.read',
    route: '/ward/bed-management',
    beforeStart: ['Understand: Department is clinical specialty; Ward is physical care unit.'],
    steps: [
      'Hierarchy: Hospital → Ward → optional Floor → Room → Bed/Cot.',
      'Doctor recommends admission/ward from consultation — does NOT pick physical bed.',
      'Ward Receptionist performs actual admission and room/bed allocation.',
      'Use Ward Bed Management (`/ward/bed-management`) to review occupancy.',
      'Room transfer releases old bed and occupies new bed with history preserved.',
      'Discharge releases bed/cot automatically.',
    ],
    after: ['Occupancy reflects current patients; historical records keep prior room/bed labels.'],
    related: ['how-to-admit-patient', 'how-to-discharge-patient'],
  },
  {
    id: 'ward-nursing-care',
    slug: 'ward-nursing-care',
    title: 'Ward Nursing: Vitals, MAR, IV, Notes',
    category: 'Nursing',
    keywords: ['vitals', 'mar', 'nursing', 'iv', 'drip', 'notes'],
    whoCan: 'Nurse',
    permissions: 'ward.nursing.read',
    route: '/ward/vitals',
    beforeStart: ['Patient must be admitted with active encounter.'],
    steps: [
      'Open Ward modules: Vitals (`/ward/vitals`), MAR (`/ward/mar`), Drips/IV (`/ward/drips-iv`).',
      'Select admitted patient and record observations or administrations.',
      'Use Orders & Services for ward treatment items when ordered.',
    ],
    after: ['Clinical records linked to admission encounter. Billable ward services post to encounter ledger.'],
    related: ['how-to-admit-patient', 'pharmacy-ward-medicine'],
  },
  {
    id: 'pharmacy-ward-medicine',
    slug: 'pharmacy-ward-medicine',
    title: 'Ward Medicine Request & Pharmacy Issue',
    category: 'Pharmacy',
    keywords: ['pharmacy', 'medicine', 'ward request', 'issue', 'mar', 'pharmacy sale', 'pos'],
    searchAliases: ['pharmacy sale', 'medicine issue', 'issue medicine', 'pos sale'],
    whoCan: 'Nurse, Pharmacist',
    permissions: 'pharmacy.ward_requests.read',
    route: '/pharmacy/ward-requests',
    beforeStart: ['Admitted patient with active encounter.'],
    steps: [
      'Nurse creates ward medicine request from ward/pharmacy workflow.',
      'Pharmacist opens Pharmacy → Ward Requests (`/pharmacy/ward-requests`).',
      'Issue medicines — inventory decreases once; revenue and COGS post per encounter pharmacy model.',
      'Nurse administers via MAR (`/ward/mar`) when applicable.',
    ],
    after: ['Pharmacy charge on patient encounter ledger; stock updated.'],
    financial: ['One pharmacy revenue event and one COGS event — not duplicated in legacy Bill.'],
    related: ['ward-nursing-care', 'patient-ledger-payments'],
  },
  {
    id: 'laboratory-orders',
    slug: 'laboratory-orders',
    title: 'Laboratory Orders & Results',
    category: 'Laboratory',
    keywords: ['lab', 'laboratory', 'test', 'order'],
    whoCan: 'Doctor, Laboratory staff',
    permissions: 'laboratory.read',
    route: '/laboratory',
    beforeStart: ['Patient encounter or appointment context required.'],
    steps: [
      'Create lab order from prescription or laboratory module.',
      'Laboratory processes order and enters results.',
      'Lab charge posts to encounter ledger and GL when completed/billed.',
    ],
    after: ['Results visible in clinical/lab views; charge on patient ledger.'],
    related: ['doctor-consultation-flow', 'department-performance-report'],
  },
  {
    id: 'operations-procedures',
    slug: 'operations-procedures',
    title: 'Procedures & Operations',
    category: 'Procedures / Operations',
    keywords: ['operation', 'procedure', 'scheduled', 'complete', 'surgery'],
    whoCan: 'Doctor, Ward staff',
    permissions: 'ward.read',
    route: '/ward/patient-detail',
    beforeStart: ['Patient must be admitted for IPD operations.'],
    steps: [
      'Open admitted patient detail (`/ward/patient-detail/:admissionId`).',
      'Create Operation — status SCHEDULED creates no revenue.',
      'Mark IN_PROGRESS / COMPLETED — exactly one procedure charge and GL event on completion.',
      'Repeat completion must not duplicate charge (idempotent source key).',
    ],
    after: ['Operation charge on encounter ledger; visible in running bill.'],
    financial: ['SCHEDULED = zero revenue. COMPLETED = one charge + one GL posting.'],
    related: ['how-to-discharge-patient', 'maternity-newborn-flow'],
  },
  {
    id: 'patient-ledger-payments',
    slug: 'patient-ledger-payments',
    title: 'Patient Ledger & Payments',
    category: 'Billing / Accounts',
    keywords: ['ledger', 'payment', 'receipt', 'collect', 'balance'],
    whoCan: 'Cashier, Accountant, Ward Receptionist',
    permissions: 'ledger_payments.read',
    route: '/payments/ledger',
    beforeStart: ['Patient must have an open or recent encounter.'],
    steps: [
      'Open Patient Ledger (`/payments/ledger`) or ward payment workflow.',
      'Review charges by source (consultation, bed, lab, pharmacy, etc.).',
      'Collect payment — recorded in ledger_payments with receipt number.',
      'Payment flows to Daily Collections, Cash/Bank Book, and GL.',
    ],
    after: ['Encounter balance updated; receipt available for printing.'],
    financial: ['All received payments must appear in ledger_payments — if visible in UI but missing here, report as defect.'],
    related: ['how-to-discharge-patient', 'accounts-overview'],
  },
  {
    id: 'how-to-discharge-patient',
    slug: 'how-to-discharge-patient',
    title: 'How to Discharge a Patient',
    category: 'Admissions / IPD',
    keywords: ['discharge', 'final bill', 'invoice', 'statement'],
    whoCan: 'Ward Receptionist, Cashier',
    permissions: 'room_allotments.update',
    route: '/ward/patient-detail',
    beforeStart: ['All billable services should be posted; review Running Bill first.'],
    steps: [
      'Open patient detail → review Running Bill / Discharge Statement tab.',
      'Verify gross charges, advance, security, payments, outstanding.',
      'Collect final payment through ward/cashier workflow.',
      'Complete discharge — encounter status = discharged; bed released.',
      'Print/download final invoice/statement.',
    ],
    after: ['Room/bed available again. Final statement shows source-wise charges without Mongo IDs.'],
    financial: ['Bed charges finalized per rules; security not counted as revenue.'],
    related: ['patient-ledger-payments', 'room-bed-hierarchy'],
  },
  {
    id: 'accounts-overview',
    slug: 'accounts-overview',
    title: 'Accounts & General Ledger',
    category: 'Billing / Accounts',
    keywords: ['accounts', 'gl', 'trial balance', 'cash book', 'reconciliation'],
    whoCan: 'Accountant, Company Owner',
    permissions: 'accounts.read',
    route: '/accounts/dashboard',
    beforeStart: ['Accountant role or accounts.read permission required.'],
    steps: [
      'Open Accounts Dashboard (`/accounts/dashboard`).',
      'Use GL, Trial Balance, P&L, Cash Book, Bank Book, Receivables, Reconciliation as needed.',
      'Financial chain: Encounter → ledger_items → ledger_payments → GL journals.',
      'Do not sum legacy Bill + Ledger + GL for the same event.',
    ],
    after: ['Trial Balance should remain balanced (Debit = Credit).'],
    related: ['department-performance-report', 'patient-ledger-payments'],
  },
  {
    id: 'department-performance-report',
    slug: 'department-performance-report',
    title: 'Department Performance Report',
    category: 'Reports',
    keywords: ['department', 'report', 'performance', 'revenue', 'excel', 'pdf'],
    whoCan: 'Accountant, Company Owner',
    permissions: 'accounts.reports.read',
    route: '/accounts/department-performance',
    beforeStart: ['Select date range and optional filters.'],
    steps: [
      'Open Accounts → Department Report (`/accounts/department-performance`).',
      'Apply filters: date preset, department, doctor, OPD/IPD, source type, payment status.',
      'Review KPI cards and department/doctor/transaction tabs.',
      'Export Excel or Print/PDF for sharing.',
    ],
    after: ['Department attribution from encounter → appointment.departmentId or consultant doctor department. Unassigned shown when not attributable.'],
    financial: ['Gross Contribution = Gross Charges − Known Direct Cost (pharmacy COGS where available). Not full net profit.'],
    related: ['accounts-overview'],
  },
  {
    id: 'maternity-newborn-flow',
    slug: 'maternity-newborn-flow',
    title: 'Maternity → Birth → Nursery Flow',
    category: 'Nursery / Newborn',
    keywords: ['maternity', 'newborn', 'baby', 'nursery', 'birth', 'mother'],
    whoCan: 'Doctor, Ward/Nursery staff',
    permissions: 'nursery.read',
    route: '/ward/nursery',
    beforeStart: ['Mother must be admitted; gyne/OB consultation completed.'],
    steps: [
      'Doctor: consultation → Admission Recommendation → Ward admits mother to maternity ward/room.',
      'Complete operation/delivery when applicable (revenue on COMPLETED only).',
      'Nursery → Record Birth (`/ward/nursery/birth-records`) — search mother by name/MR.',
      'Create newborn patient — baby gets own MR, Patient, and Encounter.',
      'Register in Nursery (`/ward/nursery`) and allocate nursery cot/bed.',
      'Baby treatments use baby encounter — not mother encounter.',
      'Mother and baby discharge independently.',
    ],
    after: ['Mother↔Baby link preserved; separate occupancy and billing.'],
    related: ['birth-certificate-issue', 'room-bed-hierarchy'],
  },
  {
    id: 'birth-certificate-issue',
    slug: 'birth-certificate-issue',
    title: 'Birth Records & Hospital Birth Certificate',
    category: 'Birth Records / Certificates',
    keywords: ['birth certificate', 'birth record', 'qr', 'verify', 'pdf', 'baby certificate'],
    searchAliases: ['baby certificate', 'birth certificate', 'qr verify', 'certificate verify'],
    whoCan: 'Authorized nursery/birth records staff',
    permissions: 'birth_records.read',
    route: '/ward/nursery/birth-records',
    beforeStart: ['Birth must be recorded; verification steps completed per hospital policy.'],
    steps: [
      'Open Birth Records (`/ward/nursery/birth-records`).',
      'Find birth record — verify details (baby MR, mother, DOB, delivery mode).',
      'Issue Hospital Birth Certificate when approved.',
      'View/Print/Download PDF — includes certificate number, QR code, hospital branding.',
      'Public verification: `/verify/birth/:code` shows VALID with minimal public info only.',
    ],
    after: ['Certificate version tracked; superseded versions marked when corrected.'],
    financial: ['Birth certificate is administrative/clinical unless certificate fee explicitly configured.'],
    errors: ['Public verify page must NOT expose CNIC, billing, medications, or room history.'],
    related: ['maternity-newborn-flow'],
  },
  {
    id: 'roles-permissions',
    slug: 'roles-permissions',
    title: 'Roles & Permissions',
    category: 'Roles & Permissions',
    keywords: ['role', 'permission', 'access', '403', 'menu'],
    whoCan: 'Company Owner, Admin',
    permissions: 'roles.read',
    route: '/roles',
    navigationPath: ['Admin', 'Roles'],
    shortDescription: 'Configure who can access each hospital module and action.',
    tip: 'Menu visibility follows role permissions — direct URL access without permission returns 403.',
    beforeStart: ['Changes affect all users assigned to a role.'],
    steps: [
      'Open Roles (`/roles`) to review permission sets.',
      'Doctor: prescriptions, admission recommendations — not bed allocation.',
      'Ward Receptionist: admissions, room/bed — not GL posting.',
      'Accountant: accounts reports — not clinical modules.',
      'Direct URL access without permission returns 403 from backend.',
    ],
    after: ['Menu visibility matches role permissions.'],
    related: ['getting-started-overview'],
  },
  {
    id: 'what-happens-after-admission',
    slug: 'what-happens-after-admission',
    title: 'What Happens After Admission?',
    category: 'Admissions / IPD',
    keywords: ['after admission', 'what next', 'control panel', 'workflow'],
    shortDescription: 'Doctor recommends; Ward Reception admits; nursing care begins on Control Panel.',
    whoCan: 'Doctor, Ward Receptionist, Nurse',
    permissions: 'ward.read',
    roles: ['doctor', 'ward'],
    module: 'ward',
    route: '/ward/patient-detail',
    beforeStart: ['Understand recommendation ≠ admission.'],
    steps: [
      'DOCTOR: Appointment → Consultation → Recommend Admission → recommendation sent (NOT admitted).',
      'WARD RECEPTION: Pending Admissions → Review & Admit → Ward/Room/Bed → Admit Patient.',
      'RESULT: RoomAllotment + admission Encounter + occupied bed.',
      'NURSE/DOCTOR: Open Ward Patient Control Panel for vitals, MAR, lab, imaging, billing, discharge.',
    ],
    after: ['All inpatient activity links to the admission encounter.'],
    related: ['doctor-recommend-admission', 'how-to-admit-patient', 'ward-control-panel'],
  },
  {
    id: 'add-doctor-order',
    slug: 'add-doctor-order',
    title: 'Add Doctor Order',
    category: 'Nursing',
    keywords: ['doctor order', 'medicine', 'lab', 'imaging', 'procedure'],
    shortDescription: 'Unified modal for medicine, lab, imaging, and procedure orders from Control Panel.',
    whoCan: 'Doctor, Nurse (on behalf with Recommended By)',
    permissions: 'ward.create',
    roles: ['doctor', 'ward'],
    module: 'ward',
    route: '/ward/patient-detail',
    beforeStart: ['Patient must be admitted with active encounter.'],
    steps: [
      'Open Ward Patient Control Panel → Doctor Order quick action.',
      'Choose order type: Medicine, Lab, Imaging, Procedure, etc.',
      'Enter clinical details; ordering doctor is preserved as Recommended By.',
      'Save — order appears in Patient Updates feed and relevant tab.',
    ],
    after: ['Downstream modules (Pharmacy, Lab) receive notifications when enabled.'],
    related: ['mar-medicine-guide', 'lab-order-from-ward', 'radiology-imaging-guide'],
  },
  {
    id: 'nurse-enter-doctor-order',
    slug: 'nurse-enter-doctor-order',
    title: 'Nurse: Enter an Order Recommended by a Doctor',
    category: 'Nursing',
    keywords: ['nurse order', 'on behalf', 'recommended by', 'verbal order'],
    whoCan: 'Nurse',
    permissions: 'ward.create',
    roles: ['ward'],
    module: 'ward',
    route: '/ward/patient-detail',
    beforeStart: ['Verbal/phone order policy of your hospital applies.'],
    steps: [
      'Open Ward Patient Control Panel → Doctor Order.',
      'Select order type and enter details.',
      'Set Recommended By to the responsible consultant (required).',
      'Save — audit trail shows Entered By nurse and Recommended By doctor.',
    ],
    after: ['Laboratory and Pharmacy workflows proceed as for doctor-entered orders.'],
    related: ['add-doctor-order', 'lab-order-from-ward'],
  },
  {
    id: 'admission-history-guide',
    slug: 'admission-history-guide',
    title: 'View Previous Admission History',
    category: 'Admissions / IPD',
    keywords: ['admission history', 'prior admission', 'read only', 'discharged', 'previous admission'],
    searchAliases: ['previous admission', 'old admission', 'past admission history'],
    shortDescription: 'Read-only list of prior admissions on Control Panel and during OPD.',
    whoCan: 'Doctor, Ward staff',
    permissions: 'ward.read',
    roles: ['doctor', 'ward'],
    module: 'ward',
    route: '/ward/patient-detail',
    beforeStart: ['Patient must have prior discharged admissions.'],
    steps: [
      'During consultation or on Control Panel, open Admission History tab.',
      'Review prior Admission No, dates, doctor, ward, room/bed, diagnosis, discharge status.',
      'Open prior admission details — read-only; no edits to historical encounters.',
    ],
    after: ['Use history for clinical context; new admission creates a new encounter.'],
    related: ['how-to-discharge-patient', 'ward-control-panel'],
  },
  {
    id: 'ward-notifications-guide',
    slug: 'ward-notifications-guide',
    title: 'Use Ward Notifications',
    category: 'Nursing',
    keywords: ['notification', 'bell', 'sound', 'mute', 'admission', 'lab', 'pharmacy'],
    shortDescription: 'Hospital-scoped operational alerts with sound, mute, and deep links.',
    whoCan: 'All staff with module access',
    permissions: 'Depends on notification type',
    roles: ['doctor', 'ward', 'laboratory', 'pharmacy'],
    module: 'ward',
    beforeStart: ['Notifications have zero financial effect — they do not post ledger entries.'],
    steps: [
      'Click the bell icon in the header to open the notification panel.',
      'New actionable items play a short sound once (not on page refresh).',
      'Use Mute to silence sounds; preference persists in browser storage.',
      'Types include: Admission Recommended, Lab Order, Lab Result, Medicine Request/Issued, Imaging Order.',
      'Click a notification to open Review & Admit, Control Panel, Lab, or Pharmacy as linked.',
      'Lab/Pharmacy notifications are hidden when those modules are disabled for the hospital.',
    ],
    after: ['Mark read by opening or dismissing; unread count updates on poll.'],
    related: ['doctor-recommend-admission', 'lab-order-from-ward', 'pharmacy-ward-medicine'],
  },
  {
    id: 'troubleshooting-common',
    slug: 'troubleshooting-common',
    title: 'Common Issues & Troubleshooting',
    category: 'Troubleshooting',
    keywords: ['error', '403', 'duplicate', 'balance', 'help', 'troubleshoot'],
    whoCan: 'All users',
    permissions: 'None specific',
    beforeStart: [],
    steps: [
      '403 Forbidden: your role lacks permission — contact administrator.',
      'Payment in UI but not on ledger: report to support — payments must be in ledger_payments.',
      'Duplicate charge: check sourceType+sourceId idempotency; do not manually re-post.',
      'Department shows Unassigned: historical record lacks appointment/doctor department link.',
      'Bed unavailable: check occupancy in Bed Management; discharge or transfer first.',
    ],
    after: ['Escalate with MR No, Encounter No, and timestamp for support.'],
    related: ['patient-ledger-payments', 'room-bed-hierarchy'],
  },
];

export type { HelpSearchOptions, HelpSearchResult } from './help-search.util';

export const filterHelpArticlesByRole = (articles: HelpArticle[], roleKey: string): HelpArticle[] => {
  if (!roleKey) return articles;
  return articles.filter((article) => !article.roles?.length || article.roles.includes(roleKey));
};

export const isHelpModuleVisible = (
  module: HelpArticle['module'],
  flags: {
    clinical: boolean;
    pharmacy: boolean;
    laboratory: boolean;
    ward: boolean;
    accounts: boolean;
    nursery: boolean;
    setup: boolean;
  }
): boolean => {
  if (!module) return true;
  switch (module) {
    case 'clinical':
      return flags.clinical;
    case 'pharmacy':
      return flags.pharmacy;
    case 'laboratory':
      return flags.laboratory;
    case 'ward':
      return flags.ward;
    case 'accounts':
      return flags.accounts;
    case 'nursery':
      return flags.ward;
    case 'setup':
      return flags.setup;
    default:
      return true;
  }
};

export const getHelpArticleBySlug = (slug: string): HelpArticle | undefined =>
  HELP_ARTICLES.find((article) => article.slug === slug);

export const getHelpArticlesByCategory = (category: string): HelpArticle[] =>
  HELP_ARTICLES.filter((article) => article.category === category);
