export interface HelpArticle {
  id: string;
  slug: string;
  title: string;
  category: string;
  keywords: string[];
  /** Extra search phrases (Urdu/Roman, common typos) */
  searchAliases?: string[];
  /** One-line summary for search results */
  shortDescription?: string;
  /** When do I use this? */
  whenToUse?: string;
  /** Optional staff tip box on guide detail */
  tip?: string;
  /** User-facing menu path for Where to go */
  navigationPath?: string[];
  whoCan: string;
  permissions: string;
  /** Role filter keys: owner, doctor, nurse, receptionist, laboratory, pharmacy, accountant, ward */
  roles?: string[];
  /** Module gating for module guides */
  module?: 'clinical' | 'pharmacy' | 'laboratory' | 'ward' | 'accounts' | 'setup' | 'nursery';
  beforeStart: string[];
  steps: string[];
  after: string[];
  financial?: string[];
  errors?: string[];
  related: string[];
  route?: string;
}

export interface HelpQuickTask {
  label: string;
  slug: string;
  icon: string;
}

export interface HelpModuleGuide {
  key: string;
  title: string;
  description: string;
  icon: string;
  module: HelpArticle['module'];
  category: string;
  slug?: string;
}

export const HELP_CATEGORIES = [
  'Getting Started',
  'Patients',
  'Appointments / OPD',
  'Doctors / Prescriptions',
  'Admissions / IPD',
  'Ward / Room / Bed',
  'Nursing',
  'Pharmacy',
  'Laboratory',
  'Imaging / X-Ray',
  'Procedures / Operations',
  'Billing / Accounts',
  'Reports',
  'Nursery / Newborn',
  'Birth Records / Certificates',
  'Roles & Permissions',
  'Troubleshooting',
] as const;

/** Common search aliases → article slugs */
export const HELP_SEARCH_ALIASES: Record<string, string[]> = {
  'admit patient': ['how-to-admit-patient', 'doctor-recommend-admission'],
  admit: ['how-to-admit-patient', 'doctor-recommend-admission'],
  admission: ['how-to-admit-patient', 'doctor-recommend-admission', 'room-bed-hierarchy'],
  'ward admission': ['how-to-admit-patient', 'doctor-recommend-admission'],
  'patient admit kaise karein': ['how-to-admit-patient', 'doctor-recommend-admission'],
  'doctor ne admit forward kiya': ['how-to-admit-patient', 'doctor-recommend-admission'],
  'ward me patient admit karna': ['how-to-admit-patient'],
  'room allotment': ['how-to-admit-patient', 'room-bed-hierarchy', 'create-rooms-beds'],
  'bed assign': ['how-to-admit-patient', 'room-bed-hierarchy', 'create-rooms-beds'],
  ward: ['how-to-admit-patient', 'ward-nursing-care', 'room-bed-hierarchy', 'ward-control-panel'],
  room: ['room-bed-hierarchy', 'create-rooms-beds', 'how-to-admit-patient'],
  bed: ['room-bed-hierarchy', 'create-rooms-beds', 'how-to-admit-patient'],
  'appointment create': ['how-to-create-appointment'],
  appointment: ['how-to-create-appointment', 'doctor-consultation-flow'],
  'doctor add': ['add-doctor-guide'],
  doctor: ['doctor-consultation-flow', 'add-doctor-guide'],
  medicine: ['pharmacy-ward-medicine', 'mar-medicine-guide'],
  'medicine dose': ['mar-medicine-guide', 'pharmacy-ward-medicine'],
  'medicine kab deni hai': ['mar-medicine-guide'],
  mar: ['mar-medicine-guide', 'ward-nursing-care'],
  'lab test': ['lab-order-from-ward', 'laboratory-orders'],
  lab: ['laboratory-orders', 'lab-order-from-ward'],
  cbc: ['lab-order-from-ward', 'laboratory-orders'],
  'blood test': ['laboratory-orders', 'lab-order-from-ward'],
  xray: ['radiology-imaging-guide'],
  'x-ray': ['radiology-imaging-guide'],
  radiology: ['radiology-imaging-guide'],
  scan: ['radiology-imaging-guide'],
  'pharmacy sale': ['pharmacy-ward-medicine'],
  pos: ['pharmacy-ward-medicine'],
  'medicine issue': ['pharmacy-ward-medicine'],
  payment: ['receive-patient-payment', 'patient-ledger-payments'],
  cash: ['patient-ledger-payments', 'receive-patient-payment'],
  invoice: ['how-to-discharge-patient', 'patient-ledger-payments'],
  bill: ['how-to-discharge-patient', 'patient-ledger-payments'],
  ledger: ['patient-ledger-payments', 'accounts-overview'],
  discharge: ['how-to-discharge-patient'],
  'previous admission': ['admission-history-guide'],
  baby: ['maternity-newborn-flow', 'birth-certificate-issue', 'register-newborn'],
  newborn: ['maternity-newborn-flow', 'register-newborn'],
  'birth certificate': ['birth-certificate-issue'],
  'baby certificate': ['birth-certificate-issue'],
  'qr verify': ['birth-certificate-issue'],
  'lab reports public': ['laboratory-orders'],
  'authentication code': ['laboratory-orders', 'birth-certificate-issue'],
  'report auth code': ['laboratory-orders'],
  'hisaar360.com/lab-reports': ['laboratory-orders'],
  'hisaar360.com/verify': ['birth-certificate-issue'],
  captcha: ['birth-certificate-issue', 'laboratory-orders'],
  'medicine kaise issue karein': ['pharmacy-ward-medicine'],
  'bulk medicine': ['bulk-add-medicines'],
  'bulk medicines': ['bulk-add-medicines'],
  'excel medicine': ['bulk-add-medicines'],
  'csv medicine': ['bulk-add-medicines'],
  'import medicine': ['bulk-add-medicines'],
  'medicine import': ['bulk-add-medicines'],
  'add multiple medicines': ['bulk-add-medicines'],
  'medicine catalog': ['bulk-add-medicines', 'pharmacy-ward-medicine'],
  'duty roster': ['how-to-create-duty-roster', 'assign-nurse-duty', 'fill-open-shift'],
  roster: ['how-to-create-duty-roster', 'assign-nurse-duty'],
  'staff duty': ['how-to-create-duty-roster', 'my-duty-roster'],
  'multiple staff': ['how-to-create-duty-roster'],
  'multi staff': ['how-to-create-duty-roster'],
  'view all staff': ['how-to-create-duty-roster'],
  'digital signature': ['birth-certificate-issue', 'hospital-setup-guide'],
  'hospital stamp': ['birth-certificate-issue', 'hospital-setup-guide'],
  watermark: ['birth-certificate-issue'],
  'hisaar360.com verify': ['birth-certificate-issue'],
  'view certificate': ['birth-certificate-issue'],
  'birth certificate view': ['birth-certificate-issue'],
  'hospital seal': ['birth-certificate-issue', 'hospital-setup-guide'],
  'upload seal': ['hospital-setup-guide', 'birth-certificate-issue'],
  'upload signature': ['hospital-setup-guide', 'birth-certificate-issue'],
  'accounts rules': ['accounts-rules-guide', 'accounts-overview'],
  rules: ['accounts-rules-guide', 'accounts-overview'],
  'debit credit': ['accounts-rules-guide', 'accounts-overview'],
  'journal voucher': ['accounts-rules-guide', 'accounts-overview'],
  'cash book': ['accounts-rules-guide', 'accounts-overview'],
  'trial balance': ['accounts-rules-guide', 'accounts-overview'],
  reconciliation: ['accounts-rules-guide', 'accounts-overview'],
  'missing journal': ['accounts-rules-guide', 'accounts-overview'],
  'post missing journals': ['accounts-rules-guide', 'accounts-overview'],
  'nurse duty': ['assign-nurse-duty', 'how-to-create-duty-roster'],
  'doctor duty': ['how-to-create-duty-roster', 'my-duty-roster'],
  'ward duty': ['assign-nurse-duty', 'how-to-create-duty-roster'],
  'room duty': ['assign-nurse-duty'],
  'shift assign': ['assign-nurse-duty', 'fill-open-shift'],
  'staff shift': ['how-to-create-duty-roster', 'assign-nurse-duty'],
  'nurse shift': ['assign-nurse-duty'],
  'schedule staff': ['how-to-create-duty-roster'],
  'staff schedule': ['how-to-create-duty-roster', 'my-duty-roster'],
  'who is on duty': ['my-duty-roster', 'how-to-create-duty-roster'],
  'night duty': ['how-to-create-duty-roster', 'assign-nurse-duty'],
  'morning duty': ['how-to-create-duty-roster', 'assign-nurse-duty'],
  'open shift': ['fill-open-shift'],
  'bulk assign roster': ['bulk-assign-duty'],
  'multiple staff duty': ['bulk-assign-duty'],
  'nurse ki duty lagani hai': ['assign-nurse-duty', 'bulk-assign-duty'],
  'publish roster': ['publish-duty-roster'],
  'duty conflict': ['duty-roster-conflicts'],
  'night shift': ['how-to-create-duty-roster', 'assign-nurse-duty'],
  'duty roster kaise banaye': ['how-to-create-duty-roster'],
  'nurse ki duty kaise lagaye': ['assign-nurse-duty'],
  'ward me nurse duty': ['assign-nurse-duty'],
  'doctor ki duty lagani hai': ['how-to-create-duty-roster'],
  'room me staff assign': ['assign-nurse-duty'],
  'night shift lagani hai': ['assign-nurse-duty', 'how-to-create-duty-roster'],
  'kis ki duty hai': ['my-duty-roster'],
  'aaj kon duty par hai': ['my-duty-roster'],
};

export const HELP_QUICK_TASKS: HelpQuickTask[] = [
  { label: 'Register Patient', slug: 'how-to-register-patient', icon: 'fa-user-plus' },
  { label: 'Create Appointment', slug: 'how-to-create-appointment', icon: 'fa-calendar' },
  { label: 'Add Doctor', slug: 'add-doctor-guide', icon: 'fa-user-md' },
  { label: 'Recommend Admission', slug: 'doctor-recommend-admission', icon: 'fa-hospital-o' },
  { label: 'Admit Patient', slug: 'how-to-admit-patient', icon: 'fa-bed' },
  { label: 'Allocate Room / Bed', slug: 'room-bed-hierarchy', icon: 'fa-building' },
  { label: 'Record Vitals', slug: 'ward-nursing-care', icon: 'fa-heartbeat' },
  { label: 'Give Medicine / MAR', slug: 'mar-medicine-guide', icon: 'fa-medkit' },
  { label: 'Order Lab Test', slug: 'lab-order-from-ward', icon: 'fa-flask' },
  { label: 'Order X-Ray / Imaging', slug: 'radiology-imaging-guide', icon: 'fa-picture-o' },
  { label: 'Pharmacy Issue', slug: 'pharmacy-ward-medicine', icon: 'fa-shopping-cart' },
  { label: 'Add Medicine', slug: 'bulk-add-medicines', icon: 'fa-plus' },
  { label: 'Bulk Add Medicines', slug: 'bulk-add-medicines', icon: 'fa-table' },
  { label: 'Open Pharmacy POS', slug: 'pharmacy-ward-medicine', icon: 'fa-shopping-basket' },
  { label: 'View Inventory', slug: 'pharmacy-ward-medicine', icon: 'fa-cubes' },
  { label: 'Receive Payment', slug: 'receive-patient-payment', icon: 'fa-money' },
  { label: 'Discharge Patient', slug: 'how-to-discharge-patient', icon: 'fa-sign-out' },
  { label: 'Register Newborn', slug: 'register-newborn', icon: 'fa-child' },
  { label: 'Issue Birth Certificate', slug: 'birth-certificate-issue', icon: 'fa-certificate' },
  { label: 'Accounts Rules', slug: 'accounts-rules-guide', icon: 'fa-info-circle' },
  { label: 'Create Duty Roster', slug: 'how-to-create-duty-roster', icon: 'fa-calendar' },
  { label: 'Assign Staff Shift', slug: 'assign-nurse-duty', icon: 'fa-clock-o' },
  { label: 'Assign Nurse to Ward', slug: 'assign-nurse-duty', icon: 'fa-user-md' },
  { label: 'Open Shift', slug: 'fill-open-shift', icon: 'fa-exclamation-circle' },
  { label: 'Bulk Assign', slug: 'bulk-assign-duty', icon: 'fa-users' },
  { label: 'Duty Roster Conflict', slug: 'duty-roster-conflicts', icon: 'fa-warning' },
  { label: 'Copy Previous Week', slug: 'copy-previous-week', icon: 'fa-copy' },
  { label: 'Publish Roster', slug: 'publish-duty-roster', icon: 'fa-check' },
  { label: 'My Duty', slug: 'my-duty-roster', icon: 'fa-calendar-check-o' },
  { label: 'Staff Schedule', slug: 'my-duty-roster', icon: 'fa-users' },
];

export const HELP_MODULE_GUIDES: HelpModuleGuide[] = [
  { key: 'clinical', title: 'Clinical & OPD', description: 'Patients, appointments, doctors, prescriptions', icon: 'fa-stethoscope', module: 'clinical', category: 'Appointments / OPD', slug: 'how-to-create-appointment' },
  { key: 'ward', title: 'Ward & Nursing', description: 'Admissions, beds, vitals, MAR, discharge', icon: 'fa-heartbeat', module: 'ward', category: 'Admissions / IPD', slug: 'how-to-admit-patient' },
  { key: 'laboratory', title: 'Laboratory', description: 'Lab orders, samples, results, reports', icon: 'fa-flask', module: 'laboratory', category: 'Laboratory', slug: 'laboratory-orders' },
  { key: 'pharmacy', title: 'Pharmacy', description: 'POS, medicines, inventory, suppliers, purchases, ward requests, bulk import and reports', icon: 'fa-medkit', module: 'pharmacy', category: 'Pharmacy', slug: 'bulk-add-medicines' },
  { key: 'accounts', title: 'Accounts & Billing', description: 'Ledger, payments, GL, Rules guide, reports', icon: 'fa-book', module: 'accounts', category: 'Billing / Accounts', slug: 'accounts-overview' },
  { key: 'nursery', title: 'Nursery / Newborn', description: 'Birth records, seal/signature, certificates', icon: 'fa-child', module: 'nursery', category: 'Nursery / Newborn', slug: 'birth-certificate-issue' },
  { key: 'setup', title: 'Hospital Setup', description: 'Departments, wards, rooms, birth cert assets', icon: 'fa-hospital-o', module: 'setup', category: 'Getting Started', slug: 'hospital-setup-guide' },
  { key: 'roles', title: 'Roles & Permissions', description: 'Users, roles, and hospital access', icon: 'fa-shield', module: 'setup', category: 'Roles & Permissions', slug: 'roles-permissions' },
];

export const HELP_POPULAR_SEARCHES = [
  'admit patient',
  'medicine dose',
  'lab test',
  'x-ray',
  'payment',
  'birth certificate',
  'accounts rules',
] as const;

/** Maps popular search chips to the module that must be enabled to show them. */
export const HELP_POPULAR_SEARCH_MODULES: Record<string, HelpArticle['module']> = {
  'admit patient': 'ward',
  'medicine dose': 'ward',
  'lab test': 'laboratory',
  'x-ray': 'ward',
  payment: 'accounts',
  'birth certificate': 'nursery',
  'accounts rules': 'accounts',
};

export const HELP_ROLE_FILTERS = [
  { key: '', label: 'All Roles' },
  { key: 'owner', label: 'Owner / Admin' },
  { key: 'receptionist', label: 'Receptionist' },
  { key: 'doctor', label: 'Doctor' },
  { key: 'ward', label: 'Ward Receptionist / Nurse' },
  { key: 'laboratory', label: 'Laboratory' },
  { key: 'pharmacy', label: 'Pharmacy' },
  { key: 'accountant', label: 'Accountant' },
] as const;

export const HELP_ARTICLES: HelpArticle[] = [
  {
    id: 'getting-started-overview',
    slug: 'getting-started-overview',
    title: 'Hisaar360 HMS Overview',
    category: 'Getting Started',
    keywords: ['start', 'overview', 'hms', 'dashboard', 'workflow', 'help', 'tutorial'],
    shortDescription: 'How Help Center and module tutorials work for your hospital.',
    whoCan: 'All logged-in users',
    permissions: 'Depends on role',
    tip: 'Help Center only lists tutorials for modules enabled at your hospital (and that your role can open).',
    beforeStart: ['You must be logged in with an active hospital context.'],
    steps: [
      'Open Dashboard from the left menu.',
      'Your sidebar shows only modules enabled for this hospital (Clinical, Ward, Lab, Pharmacy, etc.).',
      'Open Help Center from the user menu — Module Guides and Quick Tasks match those enabled modules.',
      'Accounts users: use the blue Rules button on any Accounts screen for plain-language Debit/Credit help.',
      'Birth certificates: configure seal + signature in Hospital Setup before issuing.',
    ],
    after: ['Search Help for a task name (admit, payment, birth certificate, accounts rules) to open the matching guide.'],
    related: ['hospital-setup-guide', 'accounts-rules-guide', 'birth-certificate-issue'],
  },
  {
    id: 'how-to-register-patient',
    slug: 'how-to-register-patient',
    title: 'How to Register a Patient',
    category: 'Patients',
    keywords: ['patient', 'register', 'mr', 'create patient'],
    whoCan: 'Appointment Receptionist, Ward Receptionist, Company Owner',
    permissions: 'patients.create',
    roles: ['owner', 'receptionist', 'ward'],
    module: 'clinical',
    route: '/add-patient',
    beforeStart: ['Confirm CNIC/phone if your hospital requires them. Clinical module must be enabled.'],
    steps: [
      'Go to Patients → Add Patient (`/add-patient`).',
      'Enter name, gender, date of birth, phone, and address.',
      'Save — the system assigns MR No (patientNo) automatically.',
    ],
    after: ['Patient appears in All Patients and can be used for appointments and admissions.'],
    related: ['how-to-create-appointment', 'how-to-admit-patient'],
  },
  {
    id: 'how-to-create-appointment',
    slug: 'how-to-create-appointment',
    title: 'How to Create an Appointment',
    category: 'Appointments / OPD',
    keywords: ['appointment', 'opd', 'schedule', 'consultation', 'appointment create'],
    searchAliases: ['appointment create', 'book appointment', 'opd appointment'],
    whoCan: 'Appointment Receptionist',
    permissions: 'appointments.create',
    roles: ['owner', 'receptionist'],
    module: 'clinical',
    route: '/appointments',
    beforeStart: ['Patient must exist. Doctor and Department must be active. Clinical module must be enabled.'],
    steps: [
      'Open Appointments (`/appointments`).',
      'Create appointment: select patient, doctor, department, date/time.',
      'Set consultation fee if applicable and save.',
      'Collect OPD payment through supported payment workflow when required.',
    ],
    after: ['Appointment appears in doctor schedule and OPD queue. Consultation fee posts to encounter ledger when consultation is completed.'],
    financial: ['Consultation fee creates one ledger charge and one GL revenue event when finalized — not at booking alone unless configured.'],
    related: ['doctor-consultation-flow', 'how-to-admit-patient'],
  },
  {
    id: 'doctor-consultation-flow',
    slug: 'doctor-consultation-flow',
    title: 'Doctor Consultation & Prescription',
    category: 'Doctors / Prescriptions',
    keywords: ['doctor', 'consultation', 'prescription', 'diagnosis', 'admission order'],
    shortDescription: 'Complete OPD consultation, write prescription, and recommend admission when needed.',
    whenToUse: 'When a patient arrives for a scheduled appointment or walk-in consultation.',
    whoCan: 'Doctor',
    permissions: 'prescriptions.create',
    roles: ['doctor'],
    module: 'clinical',
    route: '/prescriptions',
    beforeStart: ['Patient must have an active appointment or encounter.'],
    steps: [
      'Open Prescriptions → New Prescription (`/prescriptions`).',
      'Select patient/appointment and enter clinical notes, diagnosis, medicines, lab orders.',
      'Use Admission Orders drawer to Recommend Admission when IPD is needed.',
      'Save prescription — admission recommendation does NOT allocate room/bed.',
    ],
    after: ['Prescription saved. Admission recommendation appears in Ward → Admissions → Pending.'],
    financial: ['Admission recommendation alone creates no room charge, no admission encounter, and no revenue.'],
    errors: ['If Recommend Admission is missing, check doctor permissions and prescription module access.'],
    related: ['doctor-recommend-admission', 'how-to-admit-patient', 'room-bed-hierarchy'],
  },
  {
    id: 'doctor-recommend-admission',
    slug: 'doctor-recommend-admission',
    title: 'Doctor: Recommend a Patient for Admission',
    category: 'Admissions / IPD',
    keywords: ['recommend admission', 'admission order', 'pending', 'ipd', 'doctor'],
    searchAliases: ['admission recommend', 'admit order', 'patient admit kaise karein doctor'],
    shortDescription: 'Doctor sends patient to Ward Reception — patient is NOT admitted yet.',
    whenToUse: 'After consultation when inpatient care is required.',
    whoCan: 'Doctor',
    permissions: 'prescriptions.create',
    roles: ['doctor'],
    module: 'clinical',
    route: '/prescriptions',
    navigationPath: ['Prescriptions', 'Admission Orders', 'Recommend Admission'],
    tip: 'Success message shows Order No — patient is recommended, not admitted yet.',
    beforeStart: ['Patient consultation or prescription in progress.'],
    steps: [
      'Open Appointment → start Consultation → Prescription → Admission Orders → Recommend Admission.',
      'Select recommended ward, priority, clinical reason, and supporting notes.',
      'Click Recommend Admission — success shows Order No and “WHAT HAPPENS NEXT”.',
      'RESULT: Admission Recommendation only (status pending). NO RoomAllotment. NO admission Encounter.',
      'Ward Reception receives a notification and completes Review & Admit separately.',
    ],
    after: [
      'Pending admission appears in Ward → Admissions → Pending Admissions tab.',
      'Urdu: Doctor ne recommend kar diya — patient abhi admit nahi hua. Ab Ward Reception Pending Admissions se Review & Admit karegi.',
    ],
    financial: ['No revenue, no admission encounter, no bed charge at recommendation stage.'],
    errors: ['Do not tell patient they are admitted — only recommended.'],
    related: ['how-to-admit-patient', 'doctor-consultation-flow'],
  },
  {
    id: 'how-to-admit-patient',
    slug: 'how-to-admit-patient',
    title: 'Ward Reception: Complete Patient Admission',
    category: 'Admissions / IPD',
    keywords: ['admit', 'admission', 'ward reception', 'ipd', 'pending'],
    searchAliases: ['patient admit kaise karein', 'admit patient', 'ward admit', 'doctor ne admit forward kiya', 'ward me patient admit karna'],
    shortDescription: 'Ward Reception performs actual admission with ward, room, and bed.',
    whenToUse: 'After a Doctor recommends admission.',
    whoCan: 'Ward Receptionist',
    permissions: 'room_allotments.create',
    roles: ['ward', 'owner'],
    module: 'ward',
    route: '/ward/admissions',
    navigationPath: ['Ward & Nursing', 'Admissions', 'Pending Admissions'],
    tip: 'Doctor recommendation alone does not admit the patient — Ward Reception completes Review & Admit.',
    beforeStart: ['Doctor Admission Recommendation must exist in Ward → Admissions → Pending.'],
    steps: [
      'Open Ward & Nursing → Admissions → Pending Admissions.',
      'Open the doctor recommendation (or notification) → Review & Admit.',
      'Select Ward → Room → Bed, consultant, optional nurse, advance/security if needed.',
      'Confirm Admit Patient.',
      'RESULT: one RoomAllotment + one admission Encounter + bed becomes occupied.',
      'Success screen shows Admission No and Open Patient Control Panel.',
    ],
    after: ['Patient appears in Ward patient list. Room/bed becomes occupied.'],
    financial: ['Advance/security may be collected as ledger payment — not revenue. Bed charges accrue per billing rules.'],
    errors: ['Occupied beds cannot be double-assigned. Inactive wards/rooms are not offered.'],
    related: ['doctor-recommend-admission', 'room-bed-hierarchy', 'how-to-discharge-patient'],
  },
  {
    id: 'add-doctor-guide',
    slug: 'add-doctor-guide',
    title: 'How to Add a Doctor',
    category: 'Doctors / Prescriptions',
    keywords: ['add doctor', 'create doctor', 'doctor kaise banaye', 'schedule', 'doctor add'],
    searchAliases: ['doctor add', 'new doctor', 'create doctor profile'],
    shortDescription: 'Register a new doctor with department and schedule.',
    whoCan: 'Hospital Admin, Owner',
    permissions: 'doctors.create',
    roles: ['owner'],
    module: 'clinical',
    route: '/add-doctors',
    beforeStart: ['Department must exist in Hospital Setup.'],
    steps: [
      'Open Doctors → Add Doctors (`/add-doctors`).',
      'Enter doctor name, specialty, department, contact, and fee if applicable.',
      'Save and optionally set Doctors Schedule (`/doctors-schedule`).',
    ],
    after: ['Doctor appears in appointment booking and prescription flows.'],
    related: ['how-to-create-appointment', 'doctor-consultation-flow'],
  },
  {
    id: 'hospital-setup-guide',
    slug: 'hospital-setup-guide',
    title: 'Initial Hospital Setup',
    category: 'Getting Started',
    keywords: ['setup', 'departments', 'wards', 'users', 'hospital admin'],
    shortDescription: 'Configure departments, wards, rooms, and users for go-live.',
    whoCan: 'Owner / Hospital Admin',
    permissions: 'hospitals.update',
    roles: ['owner'],
    module: 'setup',
    route: '/hospital-setup',
    beforeStart: ['Owner or hospital setup permission required.'],
    steps: [
      'Open Hospital Setup (`/hospital-setup`).',
      'Create Departments (clinical specialties).',
      'Create Wards linked to departments where applicable.',
      'Add Rooms & Beds under each ward (see Create Rooms & Beds guide).',
      'Open the Birth Certificate tab.',
      'Click Upload seal image — pick a clear PNG/JPG of the hospital stamp (image is compressed automatically).',
      'Click Upload signature image — pick the authorized signatory signature image.',
      'Set Verification base URL to `https://hisaar360.com/verify/birth` (production form page). Local: `http://localhost:4200/verify/birth`. QR codes open this form (certificate number prefilled) — they no longer auto-open the certificate.',
      'Save Settings — seal and signature are stored and embedded when staff View / Print a certificate.',
      'Create Users & assign Roles with correct permissions.',
    ],
    after: [
      'Clinical, ward, and billing workflows can use configured master data.',
      'View Certificate shows watermark, QR, seal, and signature from this setup (no broken media links).',
    ],
    related: ['create-rooms-beds', 'roles-permissions', 'birth-certificate-issue'],
  },
  {
    id: 'create-rooms-beds',
    slug: 'create-rooms-beds',
    title: 'How to Create Rooms & Beds',
    category: 'Ward / Room / Bed',
    keywords: ['create room', 'create bed', 'room kaise banaye', 'bed management'],
    shortDescription: 'Set up physical rooms and beds under wards.',
    whenToUse: 'During initial setup or when expanding ward capacity.',
    whoCan: 'Owner / Hospital Admin / Ward Admin',
    permissions: 'rooms.create',
    roles: ['owner', 'ward'],
    module: 'ward',
    route: '/hospital-setup',
    beforeStart: ['Ward must exist in Hospital Setup.'],
    steps: [
      'Open Hospital Setup → Rooms / Beds (`/hospital-setup`, Rooms tab).',
      'Select ward (and floor if used).',
      'Add Room with room type and rate.',
      'Add beds/cots under the room with bed labels.',
      'Use Ward → Bed Management to verify Available / Occupied status.',
    ],
    after: ['Beds appear for admission and nursery cot allocation.'],
    related: ['room-bed-hierarchy', 'how-to-admit-patient'],
  },
  {
    id: 'ward-control-panel',
    slug: 'ward-control-panel',
    title: 'Ward Patient Control Panel',
    category: 'Nursing',
    keywords: ['control panel', 'patient detail', 'ward patient', 'overview'],
    shortDescription: 'Central screen for one admitted patient — vitals, MAR, orders, billing.',
    whenToUse: 'After admission when managing inpatient care.',
    whoCan: 'Nurse, Ward Doctor, Ward Receptionist',
    permissions: 'ward.read',
    roles: ['ward', 'doctor'],
    module: 'ward',
    route: '/ward/patient-detail',
    beforeStart: ['Patient must be admitted with active encounter.'],
    steps: [
      'From Ward Patient List or Admissions, open patient detail.',
      'Review header: MR, admission no, ward/room/bed, consultant, diagnosis.',
      'Use action bar: Vitals, Medicine/MAR, Lab, Orders, Payment, Discharge.',
      'Use tabs for Overview, Medicines, Lab, Billing, Discharge, etc.',
    ],
    after: ['All ward activities link to the same admission encounter.'],
    related: ['ward-nursing-care', 'mar-medicine-guide', 'how-to-discharge-patient'],
  },
  {
    id: 'mar-medicine-guide',
    slug: 'mar-medicine-guide',
    title: 'Give Medicine / MAR',
    category: 'Nursing',
    keywords: ['mar', 'medicine', 'dose', 'medicine dose', 'administer', 'schedule'],
    searchAliases: ['medicine dose', 'give medicine', 'last given', 'next due', 'medicine kab deni hai', 'administer medicine'],
    shortDescription: 'Track ordered medicine, pharmacy issue, and each administered dose.',
    whenToUse: 'When inpatient medicines are ordered and need scheduled administration.',
    whoCan: 'Nurse',
    permissions: 'ward.nursing.read',
    roles: ['ward', 'doctor'],
    module: 'ward',
    route: '/ward/mar',
    beforeStart: ['Medicine ordered and pharmacy issue completed where applicable.'],
    steps: [
      'Doctor Order → medicine added (ORDERED / Recommended By doctor preserved).',
      'Nurse sends Medicine Request to Pharmacy (REQUESTED / Entered By nurse).',
      'Pharmacy issues stock (ISSUED / Issued By pharmacy user).',
      'Open Ward Patient Control Panel → Medicines / MAR or Ward → MAR.',
      'Review Last Given, Next Due, and Dose Timeline (Due, Late, Given, Held, Refused).',
      'Click a due dose → Record Administration with scheduled time, actual dose, and status.',
      'RESULT: GIVEN dose recorded with administeredBy and administeredAt — prior doses are never overwritten.',
    ],
    after: ['ORDERED ≠ REQUESTED ≠ ISSUED ≠ GIVEN — each step has a different actor and status.'],
    related: ['pharmacy-ward-medicine', 'ward-control-panel'],
  },
  {
    id: 'lab-order-from-ward',
    slug: 'lab-order-from-ward',
    title: 'Order Lab Test for Admitted Patient',
    category: 'Laboratory',
    keywords: ['lab test', 'cbc', 'blood test', 'lab order', 'lab kaise karein'],
    searchAliases: ['lab test', 'order lab', 'cbc test'],
    shortDescription: 'Order laboratory tests for an admitted patient.',
    whenToUse: 'When doctor or nurse needs new lab work during admission.',
    whoCan: 'Doctor, Nurse (on behalf of doctor)',
    permissions: 'lab_orders.create',
    roles: ['doctor', 'ward'],
    module: 'laboratory',
    route: '/ward/orders-services',
    beforeStart: ['Patient admitted with active encounter.'],
    steps: [
      'Doctor or Nurse (on behalf) opens Ward Patient Control Panel → Doctor Order → Lab.',
      'Laboratory receives order in Lab Dashboard.',
      'Lab: Collect Sample → Enter Result → Verify.',
      'Ward/Doctor receives Lab Result Ready notification.',
      'Open result from Control Panel → Laboratory tab (read-only verified result).',
    ],
    after: ['Verified result visible on ward/doctor view; charge posts to encounter ledger.'],
    related: ['laboratory-orders', 'ward-control-panel'],
  },
  {
    id: 'radiology-imaging-guide',
    slug: 'radiology-imaging-guide',
    title: 'X-Ray / Imaging Order',
    category: 'Imaging / X-Ray',
    keywords: ['xray', 'x-ray', 'radiology', 'imaging', 'scan', 'chest x-ray'],
    searchAliases: ['xray kaise karein', 'x ray order', 'xray', 'x-ray', 'scan order'],
    shortDescription: 'Imaging via Ward Doctor Orders — no dedicated Radiology module yet.',
    whenToUse: 'When imaging (e.g. Chest X-Ray) is needed during inpatient care.',
    whoCan: 'Doctor, Nurse (on behalf of doctor)',
    permissions: 'ward.read',
    roles: ['doctor', 'ward'],
    module: 'ward',
    route: '/ward/orders-services',
    beforeStart: ['Patient admitted; imaging service configured if billable.'],
    steps: [
      'Open Ward Patient Control Panel → Doctor Order → Imaging.',
      'Imaging orders such as X-Ray, Ultrasound, CT and MRI are currently recorded through Ward Doctor Orders.',
      'Select modality (e.g. X-Ray), study name, priority, and clinical indication.',
      'If nurse enters on behalf, set Recommended By doctor.',
      'Order appears in Control Panel → Imaging tab and ward notifications where configured.',
      'There is no separate Radiology module in the current release.',
    ],
    after: ['Order tracked on patient record; report available for clinical review.'],
    related: ['ward-control-panel', 'operations-procedures'],
  },
  {
    id: 'receive-patient-payment',
    slug: 'receive-patient-payment',
    title: 'How to Receive Patient Payment',
    category: 'Billing / Accounts',
    keywords: ['payment', 'receive payment', 'cash', 'payment kaise receive karein'],
    searchAliases: ['payment kaise karein', 'collect payment'],
    shortDescription: 'Collect cash/card payment against patient encounter balance.',
    whoCan: 'Cashier, Ward Receptionist, Accountant',
    permissions: 'ledger_payments.create',
    roles: ['accountant', 'ward', 'owner'],
    module: 'accounts',
    route: '/payments/addpayment',
    beforeStart: ['Patient encounter with outstanding or advance collection needed.'],
    steps: [
      'Open Payments → Add Payment (`/payments/addpayment`) or ward payment action.',
      'Select patient and encounter; enter amount and payment method.',
      'Save — receipt number generated in ledger_payments.',
    ],
    after: ['Balance updated; appears in Daily Collections and GL.'],
    financial: ['Payment is ledger_payment — not counted as duplicate revenue.'],
    related: ['patient-ledger-payments', 'how-to-discharge-patient'],
  },
  {
    id: 'register-newborn',
    slug: 'register-newborn',
    title: 'Register Newborn & Link to Mother',
    category: 'Nursery / Newborn',
    keywords: ['register newborn', 'baby', 'link mother', 'nursery'],
    shortDescription: 'Create baby patient record and nursery placement after delivery.',
    whoCan: 'Nursery / Ward staff',
    permissions: 'nursery.read',
    roles: ['ward', 'doctor'],
    module: 'nursery',
    route: '/ward/nursery/birth-records',
    beforeStart: ['Mother admitted; birth event documented.'],
    steps: [
      'Open Birth Records (`/ward/nursery/birth-records`) → Record Birth.',
      'Search mother by name/MR; enter delivery details.',
      'System creates newborn Patient with own MR and links to mother.',
      'Assign nursery cot in Nursery dashboard if applicable.',
    ],
    after: ['Baby has separate encounter for treatments and billing.'],
    related: ['maternity-newborn-flow', 'birth-certificate-issue'],
  },
  {
    id: 'room-bed-hierarchy',
    slug: 'room-bed-hierarchy',
    title: 'Department vs Ward vs Room vs Bed',
    category: 'Ward / Room / Bed',
    keywords: ['room', 'bed', 'ward', 'floor', 'transfer', 'cot', 'department', 'room allotment', 'bed assign'],
    searchAliases: ['room allotment', 'bed assign', 'allocate room', 'allocate bed'],
    whoCan: 'All clinical and ward staff',
    permissions: 'ward.read',
    roles: ['owner', 'ward', 'doctor'],
    module: 'ward',
    route: '/ward/bed-management',
    beforeStart: ['Understand: Department is clinical specialty; Ward is physical care unit. Ward module must be enabled.'],
    steps: [
      'Hierarchy: Hospital → Ward → optional Floor → Room → Bed/Cot.',
      'Doctor recommends admission/ward from consultation — does NOT pick physical bed.',
      'Ward Receptionist performs actual admission and room/bed allocation.',
      'Use Ward Bed Management (`/ward/bed-management`) to review occupancy.',
      'Room transfer releases old bed and occupies new bed with history preserved.',
      'Discharge releases bed/cot automatically.',
    ],
    after: ['Occupancy reflects current patients; historical records keep prior room/bed labels.'],
    related: ['how-to-admit-patient', 'how-to-discharge-patient'],
  },
  {
    id: 'ward-nursing-care',
    slug: 'ward-nursing-care',
    title: 'Ward Nursing: Vitals, MAR, IV, Notes',
    category: 'Nursing',
    keywords: ['vitals', 'mar', 'nursing', 'iv', 'drip', 'notes'],
    whoCan: 'Nurse',
    permissions: 'ward.nursing.read',
    roles: ['ward'],
    module: 'ward',
    route: '/ward/vitals',
    beforeStart: ['Patient must be admitted with active encounter. Ward module must be enabled.'],
    steps: [
      'Open Ward modules: Vitals (`/ward/vitals`), MAR (`/ward/mar`), Drips/IV (`/ward/drips-iv`).',
      'Select admitted patient and record observations or administrations.',
      'Use Orders & Services for ward treatment items when ordered.',
    ],
    after: ['Clinical records linked to admission encounter. Billable ward services post to encounter ledger.'],
    related: ['how-to-admit-patient', 'pharmacy-ward-medicine'],
  },
  {
    id: 'pharmacy-ward-medicine',
    slug: 'pharmacy-ward-medicine',
    title: 'Ward Medicine Request & Pharmacy Issue',
    category: 'Pharmacy',
    keywords: ['pharmacy', 'medicine', 'ward request', 'issue', 'mar', 'pharmacy sale', 'pos'],
    searchAliases: ['pharmacy sale', 'medicine issue', 'issue medicine', 'pos sale'],
    whoCan: 'Nurse, Pharmacist',
    permissions: 'pharmacy.ward_requests.read',
    roles: ['pharmacy', 'ward'],
    module: 'pharmacy',
    route: '/pharmacy/ward-requests',
    beforeStart: ['Admitted patient with active encounter. Pharmacy module must be enabled.'],
    steps: [
      'Nurse creates ward medicine request from ward/pharmacy workflow.',
      'Pharmacist opens Pharmacy → Ward Requests (`/pharmacy/ward-requests`).',
      'Issue medicines — inventory decreases once; revenue and COGS post per encounter pharmacy model.',
      'Nurse administers via MAR (`/ward/mar`) when applicable.',
    ],
    after: ['Pharmacy charge on patient encounter ledger; stock updated.'],
    financial: ['One pharmacy revenue event and one COGS event — not duplicated in legacy Bill.'],
    related: ['ward-nursing-care', 'patient-ledger-payments', 'bulk-add-medicines'],
  },
  {
    id: 'bulk-add-medicines',
    slug: 'bulk-add-medicines',
    title: 'Bulk Add Medicines',
    category: 'Pharmacy',
    keywords: [
      'bulk medicine',
      'bulk medicines',
      'excel medicine',
      'csv medicine',
      'import medicine',
      'medicine import',
      'add multiple medicines',
      'medicine catalog',
      'opening stock',
      'pharmacy stock',
      'batch',
      'expiry',
      'SKU',
      'barcode',
    ],
    searchAliases: [
      'bulk medicine',
      'excel import',
      'csv import',
      'add many medicines',
      'product management bulk',
    ],
    shortDescription: 'Import many medicines with Excel/CSV or manual rows, then save them all in one request.',
    whenToUse: 'When you need to add a large medicine catalog or opening stock for a pharmacy store quickly.',
    tip: 'Nothing is saved until you click Save All Medicines. Use Download Template before Upload File for correct columns.',
    navigationPath: ['Pharmacy', 'Medicine Catalog', 'Bulk Add Medicines'],
    whoCan: 'Pharmacy staff and Hospital Admin roles with medicine create access',
    permissions: 'products.create (opening stock also needs inventory.adjust)',
    roles: ['pharmacy', 'owner'],
    module: 'pharmacy',
    route: '/pharmacy/products/bulk',
    beforeStart: [
      'Pharmacy module must be enabled for the hospital.',
      'From Medicine Catalog, open Bulk Add Medicines.',
      'Download Template and prepare store/category names that match your hospital.',
      'Confirm medicine strength, units, cost price, and opening stock.',
      'Opening stock creates inventory rows and stock movements — it is never stored on the product itself.',
    ],
    steps: [
      'Open Pharmacy → Medicine Catalog (`/pharmacy/products`).',
      'Click Bulk Add Medicines.',
      'Click Download Template (or choose Add Manually).',
      'Fill medicine details (Medicine Name, Type, Strength, Unit, Store, Cost Price, Opening Stock).',
      'Click Upload File — parsing happens in the browser only.',
      'Review Spreadsheet Preview (or Preview on mobile).',
      'Fix every row marked Error (duplicates, missing fields, invalid store/dates).',
      'Keep Validate data before saving turned on.',
      'Click Save All Medicines once (on mobile: Save All (N) Medicines).',
      'Wait for the success confirmation — one bulk API request creates all medicines together.',
      'Return to Medicine Catalog to see the new products.',
    ],
    after: [
      'Products appear in Medicine Catalog for the store.',
      'Opening quantities appear in pharmacy inventory.',
      'Opening-stock movements exist for each imported quantity.',
      'Medicines become available to POS and ward flows according to current visibility rules.',
    ],
    errors: [
      'Duplicate SKU — change the SKU or leave blank for auto-generate.',
      'Unknown store — use the exact store name from Hospital Setup / Product Management.',
      'Invalid category — pick an existing category or ensure you can create categories.',
      'Missing required field — fill Name, Type, Strength, Strength Unit, Store, Cost Price, Opening Stock.',
      'Invalid date — use YYYY-MM-DD; expiry cannot be before manufacturing date.',
      'Duplicate barcode — remove or change barcodes that repeat in the file or already exist.',
      'Invalid Excel headers — download the template again and keep the required column titles.',
    ],
    related: [
      'pharmacy-ward-medicine',
      'patient-ledger-payments',
      'accounts-overview',
    ],
  },
  {
    id: 'laboratory-orders',
    slug: 'laboratory-orders',
    title: 'Laboratory Orders & Results',
    category: 'Laboratory',
    keywords: ['lab', 'laboratory', 'test', 'order', 'lab reports', 'public reports', 'auth code'],
    whoCan: 'Doctor, Laboratory staff',
    permissions: 'laboratory.read',
    roles: ['laboratory', 'doctor', 'ward'],
    module: 'laboratory',
    route: '/laboratory',
    beforeStart: ['Patient encounter or appointment context required. Laboratory module must be enabled.'],
    steps: [
      'Create lab order from prescription or laboratory module.',
      'Laboratory processes order and enters results.',
      'Lab charge posts to encounter ledger and GL when completed/billed.',
      'Invoice prints File No + Report Auth Code (unique per patient).',
      'Patients open `https://hisaar360.com/lab-reports`, enter File No + Report Auth Code + Cloudflare captcha, then Search Reports — only approved/completed reports appear.',
    ],
    after: [
      'Results visible in clinical/lab views; charge on patient ledger.',
      'Public lab page never works with File No alone — Report Auth Code from the invoice is required.',
    ],
    related: ['doctor-consultation-flow', 'department-performance-report', 'birth-certificate-issue'],
  },
  {
    id: 'operations-procedures',
    slug: 'operations-procedures',
    title: 'Procedures & Operations',
    category: 'Procedures / Operations',
    keywords: ['operation', 'procedure', 'scheduled', 'complete', 'surgery'],
    whoCan: 'Doctor, Ward staff',
    permissions: 'ward.read',
    roles: ['doctor', 'ward'],
    module: 'ward',
    route: '/ward/patient-detail',
    beforeStart: ['Patient must be admitted for IPD operations. Ward module must be enabled.'],
    steps: [
      'Open admitted patient detail (`/ward/patient-detail/:admissionId`).',
      'Create Operation — status SCHEDULED creates no revenue.',
      'Mark IN_PROGRESS / COMPLETED — exactly one procedure charge and GL event on completion.',
      'Repeat completion must not duplicate charge (idempotent source key).',
    ],
    after: ['Operation charge on encounter ledger; visible in running bill.'],
    financial: ['SCHEDULED = zero revenue. COMPLETED = one charge + one GL posting.'],
    related: ['how-to-discharge-patient', 'maternity-newborn-flow'],
  },
  {
    id: 'patient-ledger-payments',
    slug: 'patient-ledger-payments',
    title: 'Patient Ledger & Payments',
    category: 'Billing / Accounts',
    keywords: ['ledger', 'payment', 'receipt', 'collect', 'balance'],
    whoCan: 'Cashier, Accountant, Ward Receptionist',
    permissions: 'ledger_payments.read',
    roles: ['accountant', 'owner', 'ward', 'receptionist'],
    module: 'accounts',
    route: '/payments/ledger',
    beforeStart: ['Patient must have an open or recent encounter.'],
    steps: [
      'Open Patient Ledger (`/payments/ledger`) or ward payment workflow.',
      'Review charges by source (consultation, bed, lab, pharmacy, etc.).',
      'Collect payment — recorded in ledger_payments with receipt number.',
      'Payment flows to Daily Collections, Cash/Bank Book, and GL.',
      'If Debit/Credit or Cash Book columns confuse you, open Accounts → Rules (easy guide).',
    ],
    after: ['Encounter balance updated; receipt available for printing.'],
    financial: ['All received payments must appear in ledger_payments — if visible in UI but missing here, report as defect.'],
    related: ['how-to-discharge-patient', 'accounts-overview', 'accounts-rules-guide'],
  },
  {
    id: 'how-to-discharge-patient',
    slug: 'how-to-discharge-patient',
    title: 'How to Discharge a Patient',
    category: 'Admissions / IPD',
    keywords: ['discharge', 'final bill', 'invoice', 'statement'],
    whoCan: 'Ward Receptionist, Cashier',
    permissions: 'room_allotments.update',
    roles: ['ward', 'accountant', 'owner'],
    module: 'ward',
    route: '/ward/patient-detail',
    beforeStart: ['All billable services should be posted; review Running Bill first. Ward module must be enabled.'],
    steps: [
      'Open patient detail → review Running Bill / Discharge Statement tab.',
      'Verify gross charges, advance, security, payments, outstanding.',
      'Collect final payment through ward/cashier workflow.',
      'Complete discharge — encounter status = discharged; bed released.',
      'Print/download final invoice/statement.',
    ],
    after: ['Room/bed available again. Final statement shows source-wise charges without Mongo IDs.'],
    financial: ['Bed charges finalized per rules; security not counted as revenue.'],
    related: ['patient-ledger-payments', 'room-bed-hierarchy'],
  },
  {
    id: 'accounts-overview',
    slug: 'accounts-overview',
    title: 'Accounts & General Ledger',
    category: 'Billing / Accounts',
    keywords: ['accounts', 'gl', 'trial balance', 'cash book', 'reconciliation', 'rules', 'journal'],
    searchAliases: ['accounts dashboard', 'general ledger', 'open accounts'],
    shortDescription: 'Open Accounts screens, use Rules for easy explanations, and read GL / Cash Book correctly.',
    tip: 'Confused by Debit = Credit on Journal? That is normal — open the Rules button for a plain-language guide.',
    whoCan: 'Accountant, Company Owner',
    permissions: 'accounts.read',
    roles: ['accountant', 'owner'],
    module: 'accounts',
    route: '/accounts/dashboard',
    navigationPath: ['Accounts', 'Dashboard'],
    beforeStart: ['Accountant role or accounts.read permission required.'],
    steps: [
      'Open Accounts Dashboard (`/accounts/dashboard`).',
      'On any Accounts view, click Rules — Easy Guide opens for Debit/Credit, Journal, Cash Book, Bank Book, and more.',
      'Use GL, Trial Balance, P&L, Cash Book, Bank Book, Receivables, Reconciliation as needed.',
      'Journal list: one row = one voucher; Debit total equaling Credit total means the entry is balanced (not double-charged).',
      'Cash Book: Receipt = cash in, Payment = cash out. Payment 0 with Receipts is normal when only cash was collected.',
      'Reconciliation (`/accounts/reconciliation`): expand error rows to see samples; click Post missing journals for LEDGER_MISSING_JOURNAL / PAYMENT_MISSING_JOURNAL, then Apply again.',
      'Financial chain: Encounter → ledger_items → ledger_payments → GL journals.',
      'Do not sum legacy Bill + Ledger + GL for the same event.',
    ],
    after: ['Trial Balance should remain balanced (Debit = Credit). Use Preview / PDF / Print on reports when sharing.'],
    related: ['accounts-rules-guide', 'department-performance-report', 'patient-ledger-payments'],
  },
  {
    id: 'accounts-rules-guide',
    slug: 'accounts-rules-guide',
    title: 'Accounts Rules — Easy Guide (non-accountant)',
    category: 'Billing / Accounts',
    keywords: [
      'rules',
      'debit',
      'credit',
      'journal',
      'cash book',
      'bank book',
      'receivables',
      'trial balance',
      'profit loss',
      'reconciliation',
      'missing journal',
      'easy guide',
    ],
    searchAliases: [
      'accounts rules',
      'debit credit',
      'journal voucher',
      'cash book payment 0',
      'what is debit',
      'what is credit',
      'rules button',
      'reconciliation',
      'post missing journals',
      'ledger missing journal',
    ],
    shortDescription: 'Plain-language meaning of Debit, Credit, Journal, Cash Book, and other Accounts screens.',
    tip: 'Open Accounts → any report → blue Rules button. The topic for the current screen opens first.',
    whenToUse: 'When Journal Debit equals Credit and it looks “wrong”, or Cash Book shows Receipt with Payment 0.',
    whoCan: 'Accountant, Cashier, Owner, anyone with Accounts access',
    permissions: 'accounts.read',
    roles: ['accountant', 'owner'],
    module: 'accounts',
    route: '/accounts/dashboard',
    navigationPath: ['Accounts', 'Rules'],
    beforeStart: ['You do not need accounting training — Rules uses everyday examples.'],
    steps: [
      'Open any Accounts page (Dashboard, Journal, Cash Book, GL, Trial Balance, etc.).',
      'Click Rules (top toolbar) — modal title: Accounts Rules — Easy Guide.',
      'Read the topic for the current screen, or pick another topic from the list.',
      'Debit & Credit: like a see-saw — both sides must match; labels are not “profit” or “loss”.',
      'Journal: one row is one full voucher story; equal Debit and Credit means balanced, not charged twice.',
      'Cash Book: only counter cash — Receipt in, Payment out; Payment 0 is OK if nothing was paid in cash.',
      'Bank Book: same idea for card / online / bank money.',
      'Receivables = patients still owe. Daily Collections = money actually collected.',
      'Trial Balance / P&L: month health checks — see Easy example in Rules.',
      'Reconciliation: if LEDGER_MISSING_JOURNAL or PAYMENT_MISSING_JOURNAL appear, expand the row, then Post missing journals, then Apply again.',
    ],
    after: [
      'Close Rules and continue working — numbers on the page are explained by the matching topic.',
      'Full Help article also available under Billing / Accounts in Help Center.',
    ],
    related: ['accounts-overview', 'patient-ledger-payments', 'receive-patient-payment'],
  },
  {
    id: 'department-performance-report',
    slug: 'department-performance-report',
    title: 'Department Performance Report',
    category: 'Reports',
    keywords: ['department', 'report', 'performance', 'revenue', 'excel', 'pdf'],
    whoCan: 'Accountant, Company Owner',
    permissions: 'accounts.reports.read',
    roles: ['accountant', 'owner'],
    module: 'accounts',
    route: '/accounts/department-performance',
    beforeStart: ['Select date range and optional filters. Accounts access required.'],
    steps: [
      'Open Accounts → Department Report (`/accounts/department-performance`).',
      'Apply filters: date preset, department, doctor, OPD/IPD, source type, payment status.',
      'Review KPI cards and department/doctor/transaction tabs.',
      'Export Excel or Print/PDF for sharing.',
      'Optional: open Rules on related Accounts screens if Debit/Credit terms are unclear.',
    ],
    after: ['Department attribution from encounter → appointment.departmentId or consultant doctor department. Unassigned shown when not attributable.'],
    financial: ['Gross Contribution = Gross Charges − Known Direct Cost (pharmacy COGS where available). Not full net profit.'],
    related: ['accounts-overview', 'accounts-rules-guide'],
  },
  {
    id: 'maternity-newborn-flow',
    slug: 'maternity-newborn-flow',
    title: 'Maternity → Birth → Nursery Flow',
    category: 'Nursery / Newborn',
    keywords: ['maternity', 'newborn', 'baby', 'nursery', 'birth', 'mother'],
    whoCan: 'Doctor, Ward/Nursery staff',
    permissions: 'nursery.read',
    roles: ['owner', 'ward', 'doctor'],
    module: 'nursery',
    route: '/ward/nursery',
    beforeStart: ['Mother must be admitted; gyne/OB consultation completed. Ward/Nursery must be enabled.'],
    steps: [
      'Doctor: consultation → Admission Recommendation → Ward admits mother to maternity ward/room.',
      'Complete operation/delivery when applicable (revenue on COMPLETED only).',
      'Nursery → Record Birth (`/ward/nursery/birth-records`) — search mother by name/MR.',
      'Create newborn patient — baby gets own MR, Patient, and Encounter.',
      'Register in Nursery (`/ward/nursery`) and allocate nursery cot/bed.',
      'Baby treatments use baby encounter — not mother encounter.',
      'Issue / View Birth Certificate after setup seal + signature (see Birth Certificate guide).',
      'Mother and baby discharge independently.',
    ],
    after: ['Mother↔Baby link preserved; separate occupancy and billing.'],
    related: ['birth-certificate-issue', 'room-bed-hierarchy'],
  },
  {
    id: 'birth-certificate-issue',
    slug: 'birth-certificate-issue',
    title: 'Birth Records & Hospital Birth Certificate',
    category: 'Birth Records / Certificates',
    keywords: [
      'birth certificate',
      'birth record',
      'qr',
      'verify',
      'pdf',
      'baby certificate',
      'view certificate',
      'reprint',
      'signature',
      'stamp',
      'seal',
      'watermark',
    ],
    searchAliases: [
      'baby certificate',
      'birth certificate',
      'qr verify',
      'certificate verify',
      'view certificate',
      'certificate dekhna',
      'hospital stamp',
      'hospital seal',
      'digital signature',
      'upload seal',
    ],
    shortDescription: 'Record birth, configure seal/signature, issue certificate, and verify via QR.',
    tip: 'Seal and signature come from Hospital Setup. View Certificate loads them in one request (embedded images + QR).',
    whoCan: 'Authorized nursery/birth records staff',
    permissions: 'birth_records.read',
    roles: ['owner', 'ward'],
    module: 'nursery',
    route: '/ward/nursery/birth-records',
    navigationPath: ['Ward', 'Nursery', 'Birth Records'],
    beforeStart: [
      'Birth must be recorded and verified per hospital policy.',
      'Hospital Setup → Birth Certificate: Upload seal image + Upload signature image → Save Settings (recommended before first issue).',
      'Ward / Nursery module must be enabled.',
    ],
    steps: [
      'Open Birth Records (`/ward/nursery/birth-records`).',
      'Find birth record — verify details (baby MR, mother, DOB, delivery mode).',
      'Issue Hospital Birth Certificate when approved.',
      'Click View Certificate — one API returns certificate data plus embedded seal, signature, logo, and QR (no broken /media links on the SPA origin).',
      'Preview shows full-page watermark; seal and signature appear at the bottom when configured.',
      'Use Preview / PDF / Print from the shared document toolbar — reprint keeps the same certificate number and version.',
      'QR on the certificate opens `https://hisaar360.com/verify/birth?certificateNo=HBC-…` (landing verify form). Visitor enters Certificate Number + Cloudflare captcha, then Verify — not a direct auto-open.',
      'View Record opens certificate metadata only (not the full print layout).',
    ],
    after: [
      'Certificate version tracked; correction creates a new ACTIVE version (ordinary reprint does not).',
      'Urdu tip: Certificate verify landing pe certificate number + captcha. Lab reports alag page: hisaar360.com/lab-reports + invoice auth code.',
    ],
    financial: ['Birth certificate is administrative/clinical unless certificate fee explicitly configured.'],
    errors: [
      'Missing seal/signature on print: upload both images in Hospital Setup → Birth Certificate and Save Settings, then reopen View Certificate.',
      'Public verify page must NOT expose CNIC, billing, medications, or room history.',
      'If QR opens but shows Not Found: confirm auth-backend `HMS_PUBLIC_API_BASE_URL` (or hospital product backendUrl) points at the live HMS API.',
    ],
    related: ['maternity-newborn-flow', 'hospital-setup-guide', 'register-newborn'],
  },
  {
    id: 'roles-permissions',
    slug: 'roles-permissions',
    title: 'Roles & Permissions',
    category: 'Roles & Permissions',
    keywords: ['role', 'permission', 'access', '403', 'menu', 'modules'],
    whoCan: 'Company Owner, Admin',
    permissions: 'roles.read',
    roles: ['owner'],
    module: 'setup',
    route: '/roles',
    navigationPath: ['Admin', 'Roles'],
    shortDescription: 'Configure who can access each hospital module and action.',
    tip: 'Help Center tutorials follow enabled hospital modules — disabled modules hide their guides.',
    beforeStart: ['Changes affect all users assigned to a role.'],
    steps: [
      'Open Roles (`/roles`) to review permission sets.',
      'Doctor: prescriptions, admission recommendations — not bed allocation.',
      'Ward Receptionist: admissions, room/bed — not GL posting.',
      'Accountant: accounts reports + Rules guide — not clinical modules.',
      'Hospital enabled modules (Clinical / Ward / Lab / Pharmacy) also control which menus and Help tutorials appear.',
      'Direct URL access without permission returns 403 from backend.',
    ],
    after: ['Menu visibility matches role permissions and enabled modules.'],
    related: ['getting-started-overview', 'hospital-setup-guide'],
  },
  {
    id: 'what-happens-after-admission',
    slug: 'what-happens-after-admission',
    title: 'What Happens After Admission?',
    category: 'Admissions / IPD',
    keywords: ['after admission', 'what next', 'control panel', 'workflow'],
    shortDescription: 'Doctor recommends; Ward Reception admits; nursing care begins on Control Panel.',
    whoCan: 'Doctor, Ward Receptionist, Nurse',
    permissions: 'ward.read',
    roles: ['doctor', 'ward'],
    module: 'ward',
    route: '/ward/patient-detail',
    beforeStart: ['Understand recommendation ≠ admission.'],
    steps: [
      'DOCTOR: Appointment → Consultation → Recommend Admission → recommendation sent (NOT admitted).',
      'WARD RECEPTION: Pending Admissions → Review & Admit → Ward/Room/Bed → Admit Patient.',
      'RESULT: RoomAllotment + admission Encounter + occupied bed.',
      'NURSE/DOCTOR: Open Ward Patient Control Panel for vitals, MAR, lab, imaging, billing, discharge.',
    ],
    after: ['All inpatient activity links to the admission encounter.'],
    related: ['doctor-recommend-admission', 'how-to-admit-patient', 'ward-control-panel'],
  },
  {
    id: 'add-doctor-order',
    slug: 'add-doctor-order',
    title: 'Add Doctor Order',
    category: 'Nursing',
    keywords: ['doctor order', 'medicine', 'lab', 'imaging', 'procedure'],
    shortDescription: 'Unified modal for medicine, lab, imaging, and procedure orders from Control Panel.',
    whoCan: 'Doctor, Nurse (on behalf with Recommended By)',
    permissions: 'ward.create',
    roles: ['doctor', 'ward'],
    module: 'ward',
    route: '/ward/patient-detail',
    beforeStart: ['Patient must be admitted with active encounter.'],
    steps: [
      'Open Ward Patient Control Panel → Doctor Order quick action.',
      'Choose order type: Medicine, Lab, Imaging, Procedure, etc.',
      'Enter clinical details; ordering doctor is preserved as Recommended By.',
      'Save — order appears in Patient Updates feed and relevant tab.',
    ],
    after: ['Downstream modules (Pharmacy, Lab) receive notifications when enabled.'],
    related: ['mar-medicine-guide', 'lab-order-from-ward', 'radiology-imaging-guide'],
  },
  {
    id: 'nurse-enter-doctor-order',
    slug: 'nurse-enter-doctor-order',
    title: 'Nurse: Enter an Order Recommended by a Doctor',
    category: 'Nursing',
    keywords: ['nurse order', 'on behalf', 'recommended by', 'verbal order'],
    whoCan: 'Nurse',
    permissions: 'ward.create',
    roles: ['ward'],
    module: 'ward',
    route: '/ward/patient-detail',
    beforeStart: ['Verbal/phone order policy of your hospital applies.'],
    steps: [
      'Open Ward Patient Control Panel → Doctor Order.',
      'Select order type and enter details.',
      'Set Recommended By to the responsible consultant (required).',
      'Save — audit trail shows Entered By nurse and Recommended By doctor.',
    ],
    after: ['Laboratory and Pharmacy workflows proceed as for doctor-entered orders.'],
    related: ['add-doctor-order', 'lab-order-from-ward'],
  },
  {
    id: 'admission-history-guide',
    slug: 'admission-history-guide',
    title: 'View Previous Admission History',
    category: 'Admissions / IPD',
    keywords: ['admission history', 'prior admission', 'read only', 'discharged', 'previous admission'],
    searchAliases: ['previous admission', 'old admission', 'past admission history'],
    shortDescription: 'Read-only list of prior admissions on Control Panel and during OPD.',
    whoCan: 'Doctor, Ward staff',
    permissions: 'ward.read',
    roles: ['doctor', 'ward'],
    module: 'ward',
    route: '/ward/patient-detail',
    beforeStart: ['Patient must have prior discharged admissions.'],
    steps: [
      'During consultation or on Control Panel, open Admission History tab.',
      'Review prior Admission No, dates, doctor, ward, room/bed, diagnosis, discharge status.',
      'Open prior admission details — read-only; no edits to historical encounters.',
    ],
    after: ['Use history for clinical context; new admission creates a new encounter.'],
    related: ['how-to-discharge-patient', 'ward-control-panel'],
  },
  {
    id: 'ward-notifications-guide',
    slug: 'ward-notifications-guide',
    title: 'Use Ward Notifications',
    category: 'Nursing',
    keywords: ['notification', 'bell', 'sound', 'mute', 'admission', 'lab', 'pharmacy'],
    shortDescription: 'Hospital-scoped operational alerts with sound, mute, and deep links.',
    whoCan: 'All staff with module access',
    permissions: 'Depends on notification type',
    roles: ['doctor', 'ward', 'laboratory', 'pharmacy'],
    module: 'ward',
    beforeStart: ['Notifications have zero financial effect — they do not post ledger entries.'],
    steps: [
      'Click the bell icon in the header to open the notification panel.',
      'New actionable items play a short sound once (not on page refresh).',
      'Use Mute to silence sounds; preference persists in browser storage.',
      'Types include: Admission Recommended, Lab Order, Lab Result, Medicine Request/Issued, Imaging Order.',
      'Click a notification to open Review & Admit, Control Panel, Lab, or Pharmacy as linked.',
      'Lab/Pharmacy notifications are hidden when those modules are disabled for the hospital.',
    ],
    after: ['Mark read by opening or dismissing; unread count updates on poll.'],
    related: ['doctor-recommend-admission', 'lab-order-from-ward', 'pharmacy-ward-medicine'],
  },
  {
    id: 'how-to-create-duty-roster',
    slug: 'how-to-create-duty-roster',
    title: 'How to Create a Duty Roster',
    category: 'Ward / Room / Bed',
    keywords: ['duty roster', 'roster', 'staff duty', 'schedule staff', 'morning duty', 'night duty', 'multiple staff', 'view all staff'],
    searchAliases: ['duty roster kaise banaye', 'staff schedule', 'ek shift mein multiple staff', 'view all staff'],
    shortDescription: 'Select a date and area, fill coverage for multiple staff per shift, then publish.',
    whoCan: 'Hospital Admin / authorized Ward Admin',
    permissions: 'ward.roster.create, ward.roster.update',
    roles: ['owner', 'ward'],
    module: 'ward',
    navigationPath: ['Ward & Nursing', 'Duty Roster'],
    beforeStart: ['Use the tree: Date → Area → Shift → Staff → Review → Assign. Multiple staff can share the same ward, date, and shift.'],
    steps: [
      'Open Ward & Nursing → Duty Roster.',
      'Select the date or week you want to schedule. Use Group By: Area / Ward / Department / Role / Staff.',
      'In the week matrix, each cell shows Morning / Afternoon / Night with staff counts.',
      'Click a shift chip to open the multi-staff popover (area, shift, time, date, green N Staff badge, staff list).',
      'Use View all N staff to sync the center day table to that area/shift/date with every assigned person.',
      'Choose a Ward, Room, Department, or OPD area from the resource tree for editing.',
      'Select Morning, Afternoon, or Night.',
      'Check required vs assigned coverage and any open positions.',
      'Click Fill Open Position or Assign Staff. The drawer opens immediately; staff load in the list.',
      'Choose available staff. Overlapping duties for the same person are blocked; different people on the same shift are allowed.',
      'Save Draft, review, then Publish.',
    ],
    after: [
      'Draft stays editable until Publish. Staff see their own My Duty view.',
      'Urdu tip: Ek shift mein kai staff dikhne chahiye. Shift chip pe click karein — list + View all se poori team center table mein aa jati hai.',
    ],
    related: ['assign-nurse-duty', 'fill-open-shift', 'publish-duty-roster'],
    route: '/ward/duty-roster',
  },
  {
    id: 'assign-nurse-duty',
    slug: 'assign-nurse-duty',
    title: 'How to Assign a Nurse to a Patient Bed',
    category: 'Ward / Room / Bed',
    keywords: ['assign nurse', 'room duty', 'nurse shift', 'ward duty', 'patient nurse'],
    searchAliases: ['nurse ki duty kaise lagaye', 'nurse ki duty lagani hai', 'ward me nurse duty', 'room me staff assign'],
    whoCan: 'Hospital Admin / Ward Admin / Nurse supervisor',
    permissions: 'ward admissions update',
    roles: ['owner', 'ward'],
    module: 'ward',
    beforeStart: ['This assigns a nurse to an admitted patient. Duty Roster Assign Staff is a different shift-scheduling workflow.'],
    steps: [
      'Open Ward & Nursing → Patient List.',
      'Open the patient and click Assign Nurse.',
      'Confirm patient, MR, ward, room/bed, and current nurse.',
      'Search eligible nurses and select one.',
      'Click Assign Nurse. Cancel closes the modal without changing the roster.',
    ],
    after: ['The patient row shows the assigned nurse. This does not create a Duty Roster shift.'],
    related: ['how-to-create-duty-roster', 'fill-open-shift'],
    route: '/ward/patient-list',
  },
  {
    id: 'fill-open-shift',
    slug: 'fill-open-shift',
    title: 'How to Fill an Open Shift',
    category: 'Ward / Room / Bed',
    keywords: ['open shift', 'coverage', 'fill shift'],
    whoCan: 'Hospital Admin / Ward Admin',
    permissions: 'ward.roster.create',
    roles: ['owner', 'ward'],
    module: 'ward',
    beforeStart: ['Open shifts appear only when a coverage requirement is greater than assigned staff.'],
    steps: [
      'Select the area and shift.',
      'Review Required / Assigned / Open.',
      'Click + Fill Open Position on the open role.',
      'Choose eligible available staff.',
      'Save. Conflicts are blocked.',
    ],
    after: ['You can set a coverage requirement for an area, day, shift, and role.'],
    related: ['how-to-create-duty-roster', 'duty-roster-conflicts'],
    route: '/ward/duty-roster',
  },
  {
    id: 'duty-roster-conflicts',
    slug: 'duty-roster-conflicts',
    title: 'Duty Roster Conflicts',
    category: 'Ward / Room / Bed',
    keywords: ['duty conflict', 'overlap', 'ROSTER_CONFLICT'],
    whoCan: 'Hospital Admin / Ward Admin',
    permissions: 'ward.roster.update',
    roles: ['owner', 'ward'],
    module: 'ward',
    beforeStart: ['Overnight night shifts (23:00–07:00) are valid and still checked for overlap.'],
    steps: [
      'If staff already work an overlapping time, save returns 409 ROSTER_CONFLICT.',
      'Edit or move the existing assignment, or pick another person.',
      'Copy Previous Week previews conflicts before confirm.',
    ],
    after: ['Hard block is overlap only. Rest-gap warnings can be added later as settings.'],
    related: ['how-to-create-duty-roster', 'copy-previous-week'],
  },
  {
    id: 'copy-previous-week',
    slug: 'copy-previous-week',
    title: 'Copy Previous Week',
    category: 'Ward / Room / Bed',
    keywords: ['copy week', 'copy roster'],
    whoCan: 'Hospital Admin',
    permissions: 'ward.roster.create',
    roles: ['owner', 'ward'],
    module: 'ward',
    beforeStart: ['Preview first. Do not copy blindly if conflicts exist.'],
    steps: [
      'Click Copy Previous Week.',
      'Review Assignments, Safe, Conflicts, Inactive Staff, Inactive Area.',
      'Confirm to copy safe rows as Draft.',
      'Fix remaining gaps, then Publish.',
    ],
    after: ['Copied rows stay Draft until you publish.'],
    related: ['publish-duty-roster'],
    route: '/ward/duty-roster',
  },
  {
    id: 'publish-duty-roster',
    slug: 'publish-duty-roster',
    title: 'Publish Duty Roster',
    category: 'Ward / Room / Bed',
    keywords: ['publish roster', 'draft', 'published'],
    whoCan: 'Hospital Admin',
    permissions: 'ward.roster.update',
    roles: ['owner', 'ward'],
    module: 'ward',
    beforeStart: ['Build in Draft, review coverage, then publish the week.'],
    steps: [
      'Review Day and Week views.',
      'Click Publish Roster for the selected week.',
      'Published assignments record publishedBy and publishedAt.',
    ],
    after: ['Staff with read-only access see their published / scheduled duties.'],
    related: ['how-to-create-duty-roster', 'my-duty-roster'],
    route: '/ward/duty-roster',
  },
  {
    id: 'my-duty-roster',
    slug: 'my-duty-roster',
    title: 'My Duty Roster',
    category: 'Ward / Room / Bed',
    keywords: ['my duty', 'who is on duty', 'staff schedule'],
    searchAliases: ['aaj kon duty par hai', 'kis ki duty hai'],
    whoCan: 'Doctors, nurses, and assigned staff',
    permissions: 'ward.roster.read',
    roles: ['doctor', 'ward'],
    module: 'ward',
    beforeStart: ['Staff do not use the full admin builder unless they have create/update permission.'],
    steps: [
      'Open Duty Roster.',
      'Your view shows today and this week.',
      'Each row shows date, shift, area/ward, room if assigned, and time.',
    ],
    after: ['Ask Admin to change an assignment. Do not invent a second calendar.'],
    related: ['how-to-create-duty-roster'],
    route: '/ward/duty-roster',
  },
  {
    id: 'bulk-assign-duty',
    slug: 'bulk-assign-duty',
    title: 'How to Bulk Assign Duty Roster',
    category: 'Ward / Room / Bed',
    keywords: ['bulk assign', 'multiple staff duty', 'bulk roster'],
    searchAliases: ['bulk assign roster', 'multiple staff duty'],
    shortDescription: 'Assign one or more staff members across a date range in four steps.',
    whoCan: 'Hospital Admin / Ward Admin',
    permissions: 'ward.roster.create',
    roles: ['owner', 'ward'],
    module: 'ward',
    navigationPath: ['Ward & Nursing', 'Duty Roster', 'Bulk Assign'],
    beforeStart: ['Use Date → Area → Shift → Coverage → Staff. Bulk Assign repeats that for many days.'],
    steps: [
      'Open Duty Roster and click Bulk Assign.',
      'Step 1 Select Area: pick a Ward, Room, Department, OPD, Laboratory, Pharmacy or Support area.',
      'Step 2 Choose Shift: Morning / Afternoon / Night, plus optional date range.',
      'Step 3 Select Staff: search, filter role, and tick eligible staff. Preview is not called yet.',
      'Step 4 Review, then Save Draft or Assign Staff.',
    ],
    after: ['Backend overlap remains 409 ROSTER_CONFLICT. Preview first, then commit.'],
    related: ['how-to-create-duty-roster', 'fill-open-shift', 'duty-roster-conflicts'],
    route: '/ward/duty-roster',
  },
  {
    id: 'troubleshooting-common',
    slug: 'troubleshooting-common',
    title: 'Common Issues & Troubleshooting',
    category: 'Troubleshooting',
    keywords: ['error', '403', 'duplicate', 'balance', 'help', 'troubleshoot'],
    whoCan: 'All users',
    permissions: 'None specific',
    beforeStart: [],
    steps: [
      '403 Forbidden: your role lacks permission — contact administrator.',
      'Payment in UI but not on ledger: report to support — payments must be in ledger_payments.',
      'Duplicate charge: check sourceType+sourceId idempotency; do not manually re-post.',
      'Department shows Unassigned: historical record lacks appointment/doctor department link.',
      'Bed unavailable: check occupancy in Bed Management; discharge or transfer first.',
    ],
    after: ['Escalate with MR No, Encounter No, and timestamp for support.'],
    related: ['patient-ledger-payments', 'room-bed-hierarchy'],
  },
];

export type { HelpSearchOptions, HelpSearchResult } from './help-search.util';

export const filterHelpArticlesByRole = (articles: HelpArticle[], roleKey: string): HelpArticle[] => {
  if (!roleKey) return articles;
  return articles.filter((article) => !article.roles?.length || article.roles.includes(roleKey));
};

export const isHelpModuleVisible = (
  module: HelpArticle['module'],
  flags: {
    clinical: boolean;
    pharmacy: boolean;
    laboratory: boolean;
    ward: boolean;
    accounts: boolean;
    nursery: boolean;
    setup: boolean;
  }
): boolean => {
  if (!module) return true;
  switch (module) {
    case 'clinical':
      return flags.clinical;
    case 'pharmacy':
      return flags.pharmacy;
    case 'laboratory':
      return flags.laboratory;
    case 'ward':
      return flags.ward;
    case 'accounts':
      return flags.accounts;
    case 'nursery':
      return flags.nursery;
    case 'setup':
      return flags.setup;
    default:
      return true;
  }
};

export const getHelpArticleBySlug = (slug: string): HelpArticle | undefined =>
  HELP_ARTICLES.find((article) => article.slug === slug);

export const getHelpArticlesByCategory = (category: string): HelpArticle[] =>
  HELP_ARTICLES.filter((article) => article.category === category);
